INSERT INTO artist_albums (index, artist, album, genre, type, cover_name, cover_idx)
VALUES
	(0,'White Lion','The Best Of White Lion','Rock','Download','white_lion.jpg',460),
	(1,'Dave Dee, Dozy, Beaky, Mick & Tich','Hold Tight! - Single','Rock','Download',NULL,NULL),
	(2,'Willie Nelson and Leon Russel','Willie Nelson and Leon Russel','Country','Vinyl','WillieNelsonAndLeonRussell.jpg',462),
	(3,'Blue Swede','Hooked On a Feeling - Single','Rock','Download',NULL,NULL),
	(4,'Polecat','Fire On The Hill','Country','Download',NULL,NULL),
	(5,'Ringo Starr','Photograph_ The Digital Greatest Hits','Rock','Download',NULL,NULL),
	(6,'Ringo Starr','Photograph_ The Very Best Of Ringo Starr','Rock','download',NULL,NULL),
	(7,'Traffic','Traffic','Rock','CD',NULL,NULL),
	(8,'Traffic','When The Eagle Flies','Rock','Vinyl','Traffic_When The Eagle Flies.jpeg',459),
	(9,'Traffic','Welcome To The Canteen [Live]','Rock','download',NULL,NULL),
	(10,'North Mississippi Allstars','51 Phantom','Blues','Download',NULL,NULL),
	(11,'North Mississippi Allstars','Shake Hands With Shorty','Blues','Download',NULL,NULL),
	(12,'Tony Burgos & His Swing Shift Orchestra','Swing Now_ East Coast','Jazz','Download',NULL,NULL),
	(13,'Cold War Kids','Mine Is Yours (Deluxe Version)','Pop','Download',NULL,NULL),
	(14,'Golden Earring','Moontan','Rock','Download',NULL,NULL),
	(15,'Johnny Cash','Classic Country Hits of the 1960s with Songs','Country','Download',NULL,NULL),
	(16,'Johnny Cash','Sunday Morning Coming Down','Country','Vinyl',NULL,NULL),
	(17,'Les McCann','Live At Montreux','Jazz','Download',NULL,NULL),
	(18,'Little Eva','The Loco-Motion','Soul','Download',NULL,NULL),
	(19,'Santo And Johnny','50''s Rock','Rock','Tape',NULL,NULL),
	(20,'Uncle Earl','She Waits for Night','BlueGrass','CD',NULL,NULL),
	(21,'Uncle Earl','Waterloo, Tennessee','BlueGrass','CD',NULL,NULL),
	(22,'Alison Krauss','Forget About It','Country','CD',NULL,NULL),
	(23,'Alison Krauss','A Hundred Miles or More - A Collection','Country','Download',NULL,NULL),
	(24,'Bee Gees','Number Ones','Folk','Download',NULL,NULL),
	(25,'Bee Gees','Main Course','Folk','Vinyl',NULL,NULL),
	(26,'Bee Gees','Best Of The BeeGees','Folk','Vinyl',NULL,NULL),
	(27,'Bee Gees','Mr. Natural','Folk','Vinyl',NULL,NULL),
	(28,'Pat Metheny Group','American Garage','Jazz','Vinyl',NULL,NULL),
	(29,'Jeremy Camp','Beyond Measure (Special Edition)','Pop','Download',NULL,NULL),
	(30,'Jeremy Camp','Restored','Pop','Download',NULL,NULL),
	(31,'The Kingston Trio','Absolutely The Best','Folk','CD',NULL,NULL),
	(32,'Waylon Jennings & The Waylors','Early Years','Country','Download',NULL,NULL),
	(33,'Jerry Jeff Walker','20th Century Masters - The Millennium Collection_ The Best of Jerry Jeff Walker','Country','Download',NULL,NULL),
	(34,'Bill Perry','Fire It Up','Rock','Download',NULL,NULL),
	(35,'Billy Holliday','Best Of Billy Holliday','Blues','Vinyl',NULL,NULL),
	(36,'Fats Waller','Fats Waller_ Very Best of Fats Waller','Jazz','CD',NULL,NULL),
	(37,'Mark Knopfler','The Ragpicker''s Dream','Rock','Download',NULL,NULL),
	(38,'Mark Knopfler','Sailing To Philadelphia','Rock','Download',NULL,NULL),
	(39,'Mark Knopfler','Golden Heart','Rock','Download',NULL,NULL),
	(40,'Zac Brown Band','Keep Me In Mind - Single','Country','Download',NULL,NULL),
	(41,'Zac Brown Band','JEKYLL + HYDE','Country','Download',NULL,NULL),
	(42,'Zac Brown Band','Greatest Hits So Far','Country','Download',NULL,NULL),
	(43,'Zac Brown Band','Pass The Jar_ Zac Brown Band And Friends Live From The Fabulous Fox Theatre In Atlanta [Disc 1]','Country','download',NULL,NULL),
	(44,'Zac Brown Band','Pass The Jar_ Zac Brown Band And Friends Live From The Fabulous Fox Theatre In Atlanta [Disc 2]','Country','download',NULL,NULL),
	(45,'Mark Knopfler_Emmylou Harris','All the Road Running','Rock','Download',NULL,NULL),
	(46,'George Harrison','Let It Roll - Songs of George Harrison (Remastered)','Rock','Download',NULL,NULL),
	(47,'The Byrds','Super Hits The Byrds','Rock','Download',NULL,NULL),
	(48,'Julio Iglesias','Tango','Classical','Download',NULL,NULL),
	(49,'k.d. lang and the Siss Boom Bang','A Sleep With No Dreaming - Single','Pop','Download',NULL,NULL),
	(50,'Josh Rouse','El Turista (Bonus Track Version)','Pop','Download',NULL,NULL),
	(51,'Wye Oak','We Were Wealth','Pop','Download',NULL,NULL),
	(52,'Darius Brubeck','Chaplin''s back','Jazz','Vinyl',NULL,NULL),
	(53,'John Coltrane','Blue Train [Expanded Edition]','Jazz','CD',NULL,NULL),
	(54,'John Coltrane','Newport ''63 [Live]','Jazz','CD',NULL,NULL),
	(55,'John Coltrane','Coltrane Live At the Village Vangard Again!','Jazz','Vinyl',NULL,NULL),
	(56,'John Coltrane','Coltrane_Prestige 7105','Jazz','Vinyl',NULL,NULL),
	(57,'John Coltrane','John Coltrane His Greatest Years','Jazz','Vinyl',NULL,NULL),
	(58,'John Coltrane','Live In Seattle [Disc 2]','Jazz','CD',NULL,NULL),
	(59,'John Coltrane','Giant Steps','Jazz','Vinyl',NULL,NULL),
	(60,'John Coltrane','My Favorite Things','Jazz','Vinyl',NULL,NULL),
	(61,'John Coltrane','Live in Seattle [Disc 1]','Jazz','CD',NULL,NULL),
	(62,'John Coltrane','Impressions','Jazz','CD',NULL,NULL),
	(63,'John Coltrane','Jazz Manifesto','Jazz','Vinyl',NULL,NULL),
	(64,'Sarah Jarosz','Follow Me Down','BlueGrass','Download',NULL,NULL),
	(65,'Sarah Jarosz','Song Up In Her Head','BlueGrass','Download',NULL,NULL),
	(66,'Philip Selway','By Some Miracle - Single','Rock','Download',NULL,NULL),
	(67,'Dave Matthews Band','Everyday','Rock','CD',NULL,NULL),
	(68,'Della Mae','This World Oft Can Be','Country','Download',NULL,NULL),
	(69,'Weather Report','Sweetnighter','Jazz','Download',NULL,NULL),
	(70,'Weather Report','8_30 (Live)','Jazz','Download',NULL,NULL),
	(71,'Weather Report','Tale Spinnin''','Jazz','Download',NULL,NULL),
	(72,'Weather Report','Night Passage','Jazz','Vinyl',NULL,NULL),
	(73,'Weather Report','Mr. Gone','Jazz','Download',NULL,NULL),
	(74,'Weather Report','Heavy Weather','Jazz','Vinyl',NULL,NULL),
	(75,'Weather Report','Black Market','Jazz','Vinyl',NULL,NULL),
	(76,'Olivia Newton-John','Olivia Newton-John','Country','Download',NULL,NULL),
	(77,'Moody Blues','Days Of Future Passed','Rock','Vinyl',NULL,NULL),
	(78,'Moody Blues','To Our Children''s Children''s Children','Rock','Vinyl',NULL,NULL),
	(79,'Moody Blues','In Search Of the Lost Chord','Rock','Vinyl',NULL,NULL),
	(80,'Ravel','Ravel_ Bolero','Classical','Download',NULL,NULL),
	(81,'Mark O''Connor','Midnight on the Water','Jazz','CD',NULL,NULL),
	(82,'Mark O''Connor','Heroes','Jazz','CD',NULL,NULL),
	(83,'Mark O''Connor','The New Nashville Cats','Jazz','CD',NULL,NULL),
	(84,'Mark O''Connor','Retrospective','Jazz','CD',NULL,NULL),
	(85,'Mark O''Connor','Liberty','Jazz','CD',NULL,NULL),
	(86,'Ben E. King','The Very Best of Ben E. King','Soul','Download',NULL,NULL),
	(87,'Creedence Clearwater Revival','Creedence Gold','Rock','Download',NULL,NULL),
	(88,'Creedence Clearwater Revival','Chronicle_ 20 Greatest Hits (24-Karat Gold Disc)','Rock','Vinyl',NULL,NULL),
	(89,'Creedence Clearwater Revival','Green River','Rock','CD',NULL,NULL),
	(90,'Creedence Clearwater Revival','Bayou Country','Rock','CD',NULL,NULL),
	(91,'Rodriguez','Cold Fact (Bonus Track Version)','Rock','Download',NULL,NULL),
	(92,'Rodriguez','Coming from Reality (Bonus Track Version)','Rock','Download',NULL,NULL),
	(93,'Paul Simon','The Afterlife - Single','Pop','Download',NULL,NULL),
	(94,'Small Faces','The Immediate Years (Disc Two)','Rock','Download',NULL,NULL),
	(95,'Deep Purple','Live In Paris 1975 [Disc 2]','Rock','download',NULL,NULL),
	(96,'Deep Purple','Machine Head','Rock','Download',NULL,NULL),
	(97,'Deep Purple','Live In Paris 1975 [Disc 1]','Rock','download',NULL,NULL),
	(98,'Deep Purple','Live In Copenhagen 1972 [Disc 2]','Rock','CD',NULL,NULL),
	(99,'Deep Purple','Deepest Purple (30th Anniversary Edition)','Rock','Download',NULL,NULL),
	(100,'Deep Purple','Copenhagen 1972 [Disc 1]','Rock','CD',NULL,NULL),
	(101,'Loreena McKennitt','A Midwinter Night''s Dream','Pop','CD',NULL,NULL),
	(102,'John Mayall & The Bluesbreakers','In the Palace of the King (A Tribute to Freddie King)','Blues','Download',NULL,NULL),
	(103,'John Mayall & The Bluesbreakers','Padlock On The Blues','Blues','Download',NULL,NULL),
	(104,'Asleep At the Wheel','Asleep At the Wheel (Live)','TexMex','Download',NULL,NULL),
	(105,'Asleep At the Wheel','Asleep At the Wheel Remembers the Alamo','TexMex','Download',NULL,NULL),
	(106,'Asleep At the Wheel','The Very Best of Asleep At the Wheel (Re-Recorded Versions)','TexMex','Download',NULL,NULL),
	(107,'Thelonious Monk Quartet With John Coltrane','At Carnegie Hall','Jazz','CD',NULL,NULL),
	(108,'The Yardbirds','Over Under Sideways Down _ Roger the Engineer (Remastered)','Rock','Download',NULL,NULL),
	(109,'The Yardbirds','The Ultimate Collection','Rock','Download',NULL,NULL),
	(110,'ZZ Top','Eliminator','Rock','Tape',NULL,NULL),
	(111,'ZZ Top','Greatest Hits','Rock','CD',NULL,NULL),
	(112,'ZZ Top','Tres Hombres','Rock','Download',NULL,NULL),
	(113,'R.E.M.','Oh My Heart - Single','Rock','Download',NULL,NULL),
	(114,'R.E.M.','In Time - The Best of R.E.M. 1988-2003','Rock','Download',NULL,NULL),
	(115,'R.E.M.','Collapse Into Now','Rock','CD',NULL,NULL),
	(116,'Gregg Allman','Live Back To Macon GA Disc 2','Blues','download',NULL,NULL),
	(117,'Gregg Allman','Low Country Blues','Blues','CD',NULL,NULL),
	(118,'Gregg Allman','Just Another Rider','Blues','Download',NULL,NULL),
	(119,'Gregg Allman','Live Back To Macon GA Disc 1','Blues','download',NULL,NULL),
	(120,'Harry Belafonte','This Is Harry Belafonte','Pop','Vinyl',NULL,NULL),
	(121,'Tom Petty & The Heartbreakers','Southern Accents','Rock','CD',NULL,NULL),
	(122,'Tom Petty & The Heartbreakers','Tom Petty & The Heartbreakers','Rock','download',NULL,NULL),
	(123,'Monsters Of Folk','Monsters Of Folk','Folk','CD',NULL,NULL),
	(124,'Alexander','Alexander','Pop','Download',NULL,NULL),
	(125,'Santana','Supernatural','TexMex','CD',NULL,NULL),
	(126,'Santana','Abraxas','TexMex','Vinyl',NULL,NULL),
	(127,'Santana','Corazon (Deluxe Version)','TexMex','Download',NULL,NULL),
	(128,'Santana','All That I Am','TexMex','CD',NULL,NULL),
	(129,'Gordon Lightfoot','Summertime Dream','Folk','Download',NULL,NULL),
	(130,'Gordon Lightfoot','Gord''s Gold','Folk','Vinyl',NULL,NULL),
	(131,'Aloe Blacc','Good Things','R&B','CD',NULL,NULL),
	(132,'Aloe Blacc','I Need a Dollar (How to Make It In America) - EP','R&B','Download',NULL,NULL),
	(133,'Ike and Tina Turner','What You Hear Is What You Get','Rock','Vinyl',NULL,NULL),
	(134,'Ritchie Valens','La Bamba','Rock','Download',NULL,NULL),
	(135,'Padraig MacMathuna','Hives Of Honeyed Sound (Blas Na Meala)','Pop','Download',NULL,NULL),
	(136,'John Prine','John Prine','Folk','CD',NULL,NULL),
	(137,'John Prine','Lost Dogs and Mixed Blessings','Folk','CD',NULL,NULL),
	(138,'John Prine','In Spite of Ourselves','Folk','CD',NULL,NULL),
	(139,'Nashville Teens','Love Is The Answer','Rock','Download',NULL,NULL),
	(140,'Jackson Browne','Standing In The Breach','Pop','CD',NULL,NULL),
	(141,'Jackson Browne','The Very Best Of Jackson Browne [Disc 2]','Pop','Download',NULL,NULL),
	(142,'Jackson Browne','The Very Best of Jackson Browne [Disc 1]','Pop','Download',NULL,NULL),
	(143,'John Fogerty','Wrote a Song for Everyone','Rock','Download',NULL,NULL),
	(144,'Miles Davis','Bitches Brew Disc 2','Jazz','Vinyl',NULL,NULL),
	(145,'Miles Davis','Kind Of Blue','Jazz','Vinyl',NULL,NULL),
	(146,'Miles Davis','Classic Ballads','Jazz','Vinyl',NULL,NULL),
	(147,'Miles Davis','Workin'' With The Miles Davis Quintet','Jazz','Vinyl',NULL,NULL),
	(148,'Miles Davis','Bitches Brew Disc 1','Jazz','Vinyl',NULL,NULL),
	(149,'Miles Davis','Birth of the Cool','Jazz','Vinyl',NULL,NULL),
	(150,'Miles Davis','Milestones','Jazz','Vinyl',NULL,NULL),
	(151,'Miles Davis','Filles De Kilimanjaro','Jazz','Vinyl',NULL,NULL),
	(152,'The Overton Berry Trio','Wheedle''s Groove_ Seattle''s Finest in Funk & Soul 1965-75','Jazz','Download',NULL,NULL),
	(153,'The Overton Berry Trio','Live at Admiral','Jazz','Download',NULL,NULL),
	(154,'The Cars','Move Like This','Rock','CD',NULL,NULL),
	(155,'The Cars','Complete Greatest Hits','Rock','Download',NULL,NULL),
	(156,'Marvin Gaye','Marvin Gaye''s Greatest Hits','R&B','Download',NULL,NULL),
	(157,'Marvin Gaye','Marvin Gaye_ Gold','R&B','Download',NULL,NULL),
	(158,'Hot Tuna','Hot Tuna','Blues','Vinyl',NULL,NULL),
	(159,'Little Richard','The Georgia Peach','Rock','Download',NULL,NULL),
	(160,'The Electric Prunes','I Had Too Much to Dream','Rock','Download',NULL,NULL),
	(161,'Desmond Dekker','Desmond Dekker_ Israelites - The Best of Desmond Dekker','Regae','Download',NULL,NULL),
	(162,'Foy Willing & The Riders Of The Purple Sage','Tumbling Tumbleweeds (10 Timeless Western Songs)','Country','Download',NULL,NULL),
	(163,'Foy Willing & The Riders Of The Purple Sage','Cool Cool Water','Country','Download',NULL,NULL),
	(164,'Earth, Wind & Fire','Earth, Wind & Fire_ Greatest Hits','Rock','download',NULL,NULL),
	(165,'The Marshall Tucker Band','The Marshall Tucker Band_ Live On Long Island - 4-18-80','Rock','Download',NULL,NULL),
	(166,'The Marshall Tucker Band','Running With The Wind','Rock','Download',NULL,NULL),
	(167,'The Marshall Tucker Band','Long Hard Ride','Rock','Download',NULL,NULL),
	(168,'Elton John','The One','Rock','CD',NULL,NULL),
	(169,'Elton John','The Captain & The Kid','Rock','Download',NULL,NULL),
	(170,'Elton John','Elton John_ Greatest Hits','Rock','Download',NULL,NULL),
	(171,'Elton John','Elton John_ The Greatest Hits 1970-2002','Rock','Download',NULL,NULL),
	(172,'Elton John','Don''t Shoot Me I''m Only the Piano Player','Rock','CD',NULL,NULL),
	(173,'Gary Burton, Steve Swallow, Roy Haynes, Tiger Okoshi','Times Square','Jazz','Download',NULL,NULL),
	(174,'Telekinesis','12 Desperate Straight Lines','Pop','Download',NULL,NULL),
	(175,'Styx','Come Sail Away - The Styx Anthology','Rock','Download',NULL,NULL),
	(176,'Styx','Cornerstone','Rock','CD',NULL,NULL),
	(177,'Styx','Styx_ Greatest Hits','Rock','Download',NULL,NULL),
	(178,'Robert Plant','Angel Dance - Single','Rock','Download',NULL,NULL),
	(179,'Nat _King_ Cole','The Christmas Song','Pop','Download',NULL,NULL),
	(180,'Eric Clapton & B.B. King','Riding With The King','Blues','CD',NULL,NULL),
	(181,'Blondie','The Best of Blondie','Rock','CD',NULL,NULL),
	(182,'Blondie','The Complete Picture','Rock','Download',NULL,NULL),
	(183,'Little Dragon','Ritual Union','Rock','Download',NULL,NULL),
	(184,'Buffalo Springfield','Retrospective_ The Best of Buffalo Springfield','Rock','CD',NULL,NULL),
	(185,'Ten Years After','Stonedhenge (Re-Presents)','Blues','Download',NULL,NULL),
	(186,'Ten Years After','Recorded Live','Blues','Download',NULL,NULL),
	(187,'Ten Years After','Undead (Remastered) [Live]','Blues','Download',NULL,NULL),
	(188,'Ten Years After','A Space In Time','Blues','Download',NULL,NULL),
	(189,'Pat Metheny Trio','Trio Live Disc 2','Jazz','CD',NULL,NULL),
	(190,'Pat Metheny Trio','Trio Live Disc 1','Jazz','CD',NULL,NULL),
	(191,'Oliver Kane','Shamrock Melodies','Classical','Download',NULL,NULL),
	(192,'Stealers Wheel','Stuck In The Middle With You (Re-Recorded _ Remastered)','Rock','Download',NULL,NULL),
	(193,'Cat Stevens','Cat Stevens_ Greatest Hits','Rock','Download',NULL,NULL),
	(194,'R.L. Burnside','Mississippi Hill Country Blues','Blues','Download',NULL,NULL),
	(195,'Heart','Beautiful Broken','Rock','CD',NULL,NULL),
	(196,'Heart','Heart_ Greatest Hits','Rock','Download',NULL,NULL),
	(197,'Redbird','Redbird','Country','Download',NULL,NULL),
	(198,'Alabama','Alabama Greatest Hits','Country','Vinyl',NULL,NULL),
	(199,'Alabama','Southern Drawl','Country','CD',NULL,NULL),
	(200,'Crosby, Stills, Nash & Young','4 Way Street (Live)','Rock','Download',NULL,NULL),
	(201,'Crosby, Stills, Nash & Young','Crosby, Stills & Nash','Rock','CD',NULL,NULL),
	(202,'Wynton Marsalis & Eric Clapton','Wynton Marsalis & Eric Clapton Play the Blues (Live from Jazz At Lincoln Center)','Jazz','Download',NULL,NULL),
	(203,'Dvorak','Dvorak''s Greatest Hits','Classical','Vinyl',NULL,NULL),
	(204,'Herman''s Hermits','The Very Best Of Herman''s Hermits','Rock','CD',NULL,NULL),
	(205,'Badfinger','The Very Best Of Badfinger','Rock','CD',NULL,NULL),
	(206,'Badfinger','Brit Rock','Rock','Download',NULL,NULL),
	(207,'Badfinger','No Matter What You Are (Re-Recorded Version)','Rock','Download',NULL,NULL),
	(208,'Badfinger','20 Best of Rockin'' 70''s (Original Artist Re-Recording)','Rock','Download',NULL,NULL),
	(209,'Badfinger','Classic Soft Rock','Rock','Download',NULL,NULL),
	(210,'Walt Weiskopf Nonet','Siren','Jazz','Download',NULL,NULL),
	(211,'The Ventures','Walk Don''t Run_ The Best of the Ventures','Rock','Download',NULL,NULL),
	(212,'Mitch Ryder & The Detroit Wheels','The Best of Mitch Ryder & the Detroit Wheels','Rock','Download',NULL,NULL),
	(213,'Guns N'' Roses','Appetite For Destruction','Rock','CD',NULL,NULL),
	(214,'Guns N'' Roses','Greatest Hits Guns N'' Roses','Rock','Download',NULL,NULL),
	(215,'Patti Smith','Easter','Rock','CD',NULL,NULL),
	(216,'Patti Smith','Gung Ho','Rock','CD',NULL,NULL),
	(217,'Patti Smith','Trampin''','Rock','Download',NULL,NULL),
	(218,'Patti Smith','Radio Ethiopia','Rock','Vinyl',NULL,NULL),
	(219,'Patti Smith','Outside Society','Rock','CD',NULL,NULL),
	(220,'Patti Smith','Gone Again','Rock','CD',NULL,NULL),
	(221,'Patti Smith','Twelve','Rock','CD',NULL,NULL),
	(222,'The Airborne Toxic Event','Half Of Something Else - Single','Pop','Download',NULL,NULL),
	(223,'Joni Mitchell','Hits','Rock','Download',NULL,NULL),
	(224,'Tim O''Brien','Songs from the Mountain','BlueGrass','CD',NULL,NULL),
	(225,'Tim O''Brien','Cornbread Nation','BlueGrass','CD',NULL,NULL),
	(226,'Bad Company','In Concert - Merchants of Cool','Rock','Download',NULL,NULL),
	(227,'John Scofield','A Go Go','Jazz','CD',NULL,NULL),
	(228,'Los Bravos','Los Bravos Single','Rock','Vinyl',NULL,NULL),
	(229,'The 5.6.7.8''s','Bomb the Twist - EP','Rock','Download',NULL,NULL),
	(230,'Carole King','Tapestry','Rock','CD',NULL,NULL),
	(231,'Stevie Ray Vaughan & Double Trouble','Texas Flood','Blues','Download',NULL,NULL),
	(232,'Stevie Ray Vaughan & Double Trouble','Stevie Ray Vaughan & Double Trouble_ Live At Carnegie Hall','Blues','Download',NULL,NULL),
	(233,'Stevie Ray Vaughan & Double Trouble','The Real Deal_ Greatest Hits, Vol. 1','Blues','Download',NULL,NULL),
	(234,'Los Lobos','Los Lobos_ Live at the Fillmore','TexMex','Download',NULL,NULL),
	(235,'Los Lobos','La Bamba (Original Motion Picture Soundtrack)','TexMex','Download',NULL,NULL),
	(236,'Los Lobos','Kiko Live','TexMex','CD',NULL,NULL),
	(237,'Bobby Darin','Mack the Knife','Rock','CD',NULL,NULL),
	(238,'Simon & Garfunkel','Greatest Hits Simon & Garfunkel','Rock','CD',NULL,NULL),
	(239,'Simon & Garfunkel','Bridge Over Troubled Water','Rock','Vinyl',NULL,NULL),
	(240,'Cody Bryant and The Riders Of The Purple Sage','Best of the West','Country','CD',NULL,NULL),
	(241,'Chicago','The Very Best Of Chicago_ Only The Beginning [Disc 2]','Rock','download',NULL,NULL),
	(242,'Chicago','Chicago Live In Japan Disc 1','Rock','download',NULL,NULL),
	(243,'Chicago','Chicago Transit Authority (Remastered)','Rock','Download',NULL,NULL),
	(244,'Chicago','The Very Best of Chicago_ Only the Beginning [Disc 1]','Rock','download',NULL,NULL),
	(245,'Chicago','Chicago','Rock','Vinyl',NULL,NULL),
	(246,'Chicago','Chicago V','Rock','CD',NULL,NULL),
	(247,'Chicago','Chicago Live In Japan [Disc 1]','Rock','download',NULL,NULL),
	(248,'Chicago','Chicago Live In Japan Disc 2','Rock','download',NULL,NULL),
	(249,'The Animals','The Best of Eric Burdon and the Animals (1966-1968)','Rock','Download',NULL,NULL),
	(250,'The Animals','The Animals Original Hits','Rock','CD',NULL,NULL),
	(251,'Alvin Lee & Ten Years Later','In Flight','Blues','Download',NULL,NULL),
	(252,'Alvin Lee & Ten Years Later','Alvin Lee & Company','Blues','download',NULL,NULL),
	(253,'Alvin Lee & Ten Years Later','Rocket Fuel','Blues','Vinyl',NULL,NULL),
	(254,'Alvin Lee & Ten Years Later','Still On the Road To Freedom','Blues','Download',NULL,NULL),
	(255,'Alvin Lee & Ten Years Later','On The Road To Freedom Alvin Lee & Mylon LeFevre','Blues','Vinyl',NULL,NULL),
	(256,'Patsy Cline','Patsy Cline''s Greatest Hits (Remastered)','Country','CD',NULL,NULL),
	(257,'David Bowie','Aladdin Sane','Rock','CD',NULL,NULL),
	(258,'David Bowie','Hunky Dory','Rock','CD',NULL,NULL),
	(259,'David Bowie','Space Oddity','Rock','download',NULL,NULL),
	(260,'David Bowie','Best of Bowie','Rock','Download',NULL,NULL),
	(261,'David Bowie','_Heroes_','Rock','download',NULL,NULL),
	(262,'David Bowie','The Best of David Bowie 1980_1987','Rock','Download',NULL,NULL),
	(263,'Mavis Staples','Only For The Lonely','R&B','CD',NULL,NULL),
	(264,'Mavis Staples','You Are Not Alone - Single','R&B','Download',NULL,NULL),
	(265,'Tom Jones','Tom Jones_ Gold (1965-1975)','Pop','Download',NULL,NULL),
	(266,'Tom Jones','Reloaded - Greatest Hits','Pop','Download',NULL,NULL),
	(267,'Richard Wagner','Wagner Through the Ages','Classical','Download',NULL,NULL),
	(268,'Duran Duran','Greatest','Rock','CD',NULL,NULL),
	(269,'Gerry Rafferty','City to City','Rock','Download',NULL,NULL),
	(270,'Boz Scaggs','Silk Degrees','Rock','download',NULL,NULL),
	(271,'Boz Scaggs','Bozz Scaggs Hits','Rock','Vinyl',NULL,NULL),
	(272,'The Charlie Daniels Band','Charlie Daniels Band A Decade Of Hits','Country','Vinyl',NULL,NULL),
	(273,'The Charlie Daniels Band','The Essential Charlie Daniels Band','Country','Download',NULL,NULL),
	(274,'The Charlie Daniels Band','Nightrider','Country','Vinyl',NULL,NULL),
	(275,'Humble Pie','Town and Country (Bonus Track Version)','Rock','Download',NULL,NULL),
	(276,'Alex Hargreaves','Prelude','Pop','Download',NULL,NULL),
	(277,'Aerosmith','Gold','Rock','Download',NULL,NULL),
	(278,'Aerosmith','Gold_ Aerosmith','Rock','Download',NULL,NULL),
	(279,'Aerosmith','Get a Grip','Rock','Download',NULL,NULL),
	(280,'Grateful Dead','Two from the Vault Disc 2','Rock','CD',NULL,NULL),
	(281,'Grateful Dead','Workingman''s Dead','Rock','CD',NULL,NULL),
	(282,'Grateful Dead','The Grateful Dead (Skull & Roses)','Rock','Download',NULL,NULL),
	(283,'Grateful Dead','In The Dark','Rock','CD',NULL,NULL),
	(284,'Grateful Dead','American Beauty','Rock','CD',NULL,NULL),
	(285,'Grateful Dead','Two from the Vault Disc 1','Rock','CD',NULL,NULL),
	(286,'Grateful Dead','Aoxomoxoa','Rock','download',NULL,NULL),
	(287,'Grateful Dead','What A Long Strange Trip','Rock','Download',NULL,NULL),
	(288,'Grateful Dead','The Best Of Fare Thee Well - Celebrating 50 Years Of Grateful Dead_ Soldier Field, Chicago, Illinois 7_3-5_15','Rock','download','GratefulDead_best_of_2015.jpg',547),
	(289,'Grateful Dead','Anthem Of The Sun','Rock','CD',NULL,NULL),
	(290,'Grateful Dead','The Grateful Dead [Bonus Tracks]','Rock','CD',NULL,NULL),
	(291,'The Doobie Brothers','Cycles','Rock','Vinyl',NULL,NULL),
	(292,'The Doobie Brothers','Best Of Doobies','Rock','Vinyl',NULL,NULL),
	(293,'The Doobie Brothers','World Gone Crazy','Rock','Vinyl',NULL,NULL),
	(294,'The Doobie Brothers','Stampede','Rock','Vinyl',NULL,NULL),
	(295,'The Doobie Brothers','The Captain And Me','Rock','Vinyl',NULL,NULL),
	(296,'The Doobie Brothers','One Step Closer','Rock','Vinyl',NULL,NULL),
	(297,'The Doobie Brothers','Takin'' It To The Streets','Rock','CD',NULL,NULL),
	(298,'The Doobie Brothers','Toulouse Street','Rock','download',NULL,NULL),
	(299,'The Doobie Brothers','What Were Vices Are Now Habits','Rock','Vinyl',NULL,NULL),
	(300,'America','The Warner Bros. Years 1971-1977','Rock','Download',NULL,NULL),
	(301,'America','History_ America''s Greatest Hits','Rock','Download',NULL,NULL),
	(302,'America','America_ The Complete Greatest Hits','Rock','Download',NULL,NULL),
	(303,'Average White Band','Person to Person (Live)','Rock','Download',NULL,NULL),
	(304,'Antonio Vivaldi','Antonio Vivaldi','Classical','Vinyl',NULL,NULL),
	(305,'Barry McGuire','Eve Of Destruction','Folk','CD',NULL,NULL),
	(306,'Bob Marley & The Wailers','Legend (Remastered)','Regae','Download',NULL,NULL),
	(307,'Buddy Holly','The Buddy Holly Collection','RockaBilly','Download',NULL,NULL),
	(308,'Brenda Lee','The Definitive Collection Brenda Lee','Country','CD',NULL,NULL),
	(309,'New Riders of the Purple Sage','Boston Music Hall - December 5, 1972','Rock','Download',NULL,NULL),
	(310,'New Riders of the Purple Sage','New Riders of the Purple Sage','Rock','Download',NULL,NULL),
	(311,'New Riders of the Purple Sage','The Best of New Riders of the Purple Sage','Rock','Download',NULL,NULL),
	(312,'New Riders of the Purple Sage','The Adventures of Panama Red','Rock','Download',NULL,NULL),
	(313,'Kiss','Rock And Roll Over','Rock','CD',NULL,NULL),
	(314,'Drive-By Truckers','Live From Austin, TX','Rock','CD',NULL,NULL),
	(315,'Drive-By Truckers','American Band','Rock','CD',NULL,NULL),
	(316,'Prince','Purple Rain','Rock','Download',NULL,NULL),
	(317,'Toto','The Essential Toto','Rock','Download',NULL,NULL),
	(318,'Dave Edmunds','Rockpile','Rock','Download',NULL,NULL),
	(319,'Wagner','A Wagner Concert','Classical','Download',NULL,NULL),
	(320,'Wagner','Bernstein Conducts Wagner','Classical','Download',NULL,NULL),
	(321,'Kris Kristofferson','Silver Tongued Devil And I','Country','Vinyl',NULL,NULL),
	(322,'Kris Kristofferson','Kristofferson','Country','CD',NULL,NULL),
	(323,'J.J. Cale','Roll On','Rock','CD',NULL,NULL),
	(324,'J.J. Cale','The Definitive Collection','Rock','CD',NULL,NULL),
	(325,'Iron Butterfly','In-A-Gadda-Da-Vida','Rock','CD',NULL,NULL),
	(326,'Jim Croce','Photographs & Memories_ His Greatest Hits','Rock','CD',NULL,NULL),
	(327,'Richie Havens','Live At the Cellar Door and At the Santa Monica Civic Auditorium','Blues','Download',NULL,NULL),
	(328,'Richie Havens','Grace of the Sun','Blues','Download',NULL,NULL),
	(329,'Richie Havens','Nobody Left to Crown','Blues','Download',NULL,NULL),
	(330,'Bob Seger','Bob Seger Greatest Hits','Rock','CD',NULL,NULL),
	(331,'Talking Heads','True Stories','Rock','Vinyl',NULL,NULL),
	(332,'Unknown Artist','IBMA Blue Grass Sample','BlueGrass','CD',NULL,NULL),
	(333,'Unknown Artist','Space Odessy Sound Track','Classical','Download','2001_A_Space_Odyssey_(soundtrack).jpg',2),
	(334,'Union Gap','Union Gap','Rock','Vinyl',NULL,NULL),
	(335,'Meat Loaf','Bat Out Of Hell','Rock','CD',NULL,NULL),
	(336,'Cheap Trick','In Color [Bonus Tracks]','Rock','CD',NULL,NULL),
	(337,'The Soundtrack Studio Stars','Sounds of Tarantino','Rock','Download',NULL,NULL),
	(338,'Neil Diamond','The Neil Diamond Collection','Rock','CD',NULL,NULL),
	(339,'Keith Urban','Keith Urban _ Fuse','Rock','download',NULL,NULL),
	(340,'Chet Atkins and Hank Snow','Reminiscing','Country','Vinyl',NULL,NULL),
	(341,'The Monkees','The Monkees Greatest Hits','Rock','CD',NULL,NULL),
	(342,'Herbie Hancock','Future 2 Future','Jazz','CD',NULL,NULL),
	(343,'Carl Perkins','Rock ''N'' Roll Legend_ Carl Perkins','RockaBilly','Download',NULL,NULL),
	(344,'Jefferson Airplane','Surrealistic Pillow','Rock','Vinyl',NULL,NULL),
	(345,'Jefferson Airplane','The Essential Jefferson Airplane [Disc 1]','Rock','download',NULL,NULL),
	(346,'Jefferson Airplane','The Essential Jefferson Airplane [Disc 2]','Rock','download',NULL,NULL),
	(347,'Boxcar Willie','The Definitive Collection of Boxcar Willie (Live)','Country','Download',NULL,NULL),
	(348,'Lou Reed','Transformer','Rock','Download',NULL,NULL),
	(349,'Pete Seeger & Arlo Guthrie','Pete Seeger & Arlo Guthrie - Together In Concert','Folk','Vinyl',NULL,NULL),
	(350,'Fleet Foxes','Helplessness Blues','Rock','Download',NULL,NULL),
	(351,'John Fahey','The Best of John Fahey 1959-1977 (Remastered)','Pop','Download',NULL,NULL),
	(352,'T. Rex','Electric Warrior (Remastered)','Rock','Download',NULL,NULL),
	(353,'Dierks Bentley','Up On the Ridge','Country','Download',NULL,NULL),
	(354,'Hank Williams','24 of Hank Williams'' Greatest Hits','Country','Download',NULL,NULL),
	(355,'Sonny & Cher','The Beat Goes On_ The Best Of Sonny & Cher','Rock','CD',NULL,NULL),
	(356,'Blue Oyster Cult','Imaginos','Rock','CD',NULL,NULL),
	(357,'Jerry Garcia Band','GarciaLive Volume Seven_ November 8th, 1976 Sophie''s Palo Alto','Rock','download',NULL,NULL),
	(358,'Lynyrd Skynyrd','Gimme Back My Bullets','Country','Vinyl',NULL,NULL),
	(359,'Lynyrd Skynyrd','One From The Road','Country','Vinyl',NULL,NULL),
	(360,'Glasser','Ring (Bonus Track Edition)','Pop','Download',NULL,NULL),
	(361,'Tommy James & The Shondells','Rhino Hi-Five_ Tommy James & the Shondells - EP','Rock','download',NULL,NULL),
	(362,'Freddie Notes & the Rudies','Montego Bay','Regae','Download',NULL,NULL),
	(363,'Led Zeppelin','The Song Remains the Same Disc 2','Rock','CD',NULL,NULL),
	(364,'Led Zeppelin','Mothership (Remastered)','Rock','Download',NULL,NULL),
	(365,'Led Zeppelin','The Song Remains the Same Disc 1','Rock','CD',NULL,NULL),
	(366,'Led Zeppelin','Physical Graffiti (Remastered)','Rock','Download',NULL,NULL),
	(367,'Commander Cody & His Lost Planet Airmen','Commander Cody & His Lost Planet Airmen','Rock','Download',NULL,NULL),
	(368,'Commander Cody & His Lost Planet Airmen','Lost in the Ozone','Rock','Download',NULL,NULL),
	(369,'We Are Augustines','Chapel Song - Single','Rock','Download',NULL,NULL),
	(370,'Black Sabbath','Black Sabbath','Rock','CD',NULL,NULL),
	(371,'Black Sabbath','Sabbath Bloody Sabbath','Rock','CD',NULL,NULL),
	(372,'Black Sabbath','Technical Ecstasy','Rock','CD',NULL,NULL),
	(373,'Mark Knopfler & Emmylou Harris','This Is Us','Rock','Download',NULL,NULL),
	(374,'The Sweet','Desolation Boulevard','Rock','Download',NULL,NULL),
	(375,'Duke Ellington','West Coast Swing','Jazz','Download',NULL,NULL),
	(376,'Muddy Waters','Authorized Bootleg - Fillmore Auditorium, San Francisco Nov. 4-6 1966','Blues','Download',NULL,NULL),
	(377,'Muddy Waters','Hard Again','Blues','Download',NULL,NULL),
	(378,'Eric Clapton','Complete Clapton [Disc 2]','Blues','download',NULL,NULL),
	(379,'Eric Clapton','Live In San Diego With Special Guest JJ Cale Disc 2','Blues','CD',NULL,NULL),
	(380,'Eric Clapton','Complete Clapton [Disc 1]','Blues','download',NULL,NULL),
	(381,'Eric Clapton','Unplugged','Blues','CD',NULL,NULL),
	(382,'Eric Clapton','No Reason To Cry','Blues','CD',NULL,NULL),
	(383,'Eric Clapton','The Cream Of Clapton','Blues','CD',NULL,NULL),
	(384,'Eric Clapton','Live In San Diego With Special Guest JJ Cale Disc 1','Blues','CD',NULL,NULL),
	(385,'The Hollies','The Hollies'' Greatest Hits','Rock','Download',NULL,NULL),
	(386,'The Hollies','Greatest Hits [Disc 1]','Rock','CD',NULL,NULL),
	(387,'The Hollies','Greatest Hits [Disc 2]','Rock','CD',NULL,NULL),
	(388,'The Everly Brothers','Cadence Classics_ Their 20 Greatest Hits','Rock','Download',NULL,NULL),
	(389,'Mannheim Steamroller','Christmas','Pop','CD',NULL,NULL),
	(390,'Lester Young','Mean To Me','Jazz','Vinyl',NULL,NULL),
	(391,'The Righteous Brothers','Anthology 1962-1974 [Disc 2]','Rock','CD',NULL,NULL),
	(392,'The Righteous Brothers','Anthology_ 1962-1974 [Disc 1]','Rock','CD',NULL,NULL),
	(393,'Clarence Gatermouth Brown','Blackjack','Blues','Download',NULL,NULL),
	(394,'The Chieftains','Down The Old Plank Road_ The Nashville Sessions','BlueGrass','CD',NULL,NULL),
	(395,'The Chieftains','The Bells Of Dublin','BlueGrass','CD',NULL,NULL),
	(396,'The Tremeloes','Here Comes My Baby _ Silence Is Golden (Re-Recorded Versions) - Single','Rock','Download',NULL,NULL),
	(397,'Arlo Guthrie','Alice''s Restaurant','Folk','Vinyl',NULL,NULL),
	(398,'Arlo Guthrie','Running Down The Road','Folk','Vinyl',NULL,NULL),
	(399,'Andre Kostelanetz and his orchestra','Strauss Waltzes','Classical','Download',NULL,NULL),
	(400,'Lesley Gore','It''s My Party_ The Mercury Anthology','Pop','Download',NULL,NULL),
	(401,'Dave Brubeck','New Wine','Jazz','CD',NULL,NULL),
	(402,'Blind Faith','Blind Faith','Rock','CD',NULL,NULL),
	(403,'The Who','The Who_ The Ultimate Collection','Rock','Download',NULL,NULL),
	(404,'The Who','Hits','Rock','Download',NULL,NULL),
	(405,'The Who','Tommy','Rock','Vinyl',NULL,NULL),
	(406,'Brewer & Shipley','One Toke Over the Line','Rock','Download',NULL,NULL),
	(407,'The Sonics','This Is the Sonics','Rock','CD',NULL,NULL),
	(408,'Bill Withers','Bill Withers'' Greatest Hits','Soul','Download',NULL,NULL),
	(409,'Neil Young','Living With War','Rock','CD',NULL,NULL),
	(410,'Neil Young','Live On Air The Lost Tapes Vol. 2','Rock','download',NULL,NULL),
	(411,'Sonny Rollins','Global Warming','Jazz','Download',NULL,NULL),
	(412,'Sonny Rollins','This Is What I Do','Jazz','Download',NULL,NULL),
	(413,'Sonny Rollins','Easy Living','Jazz','Download',NULL,NULL),
	(414,'Keith Jarrett','Solo Concerts_ Lausanne [Disc 2]','Jazz','CD',NULL,NULL),
	(415,'Keith Jarrett','La Scala','Jazz','CD',NULL,NULL),
	(416,'Keith Jarrett','Solo Concerts_ Bremen [Live]','Jazz','CD',NULL,NULL),
	(417,'Keith Jarrett','Vienna Concert [Live]','Jazz','CD',NULL,NULL),
	(418,'The Coats','The Coats Collection','Pop','CD',NULL,NULL),
	(419,'The Coats','The Boys Are Back','Pop','CD',NULL,NULL),
	(420,'Wayne Fontana & The Mindbenders','20th Century Masters - The Millennium Collection_ Wayne Fontana & The Mindbenders','Rock','Download',NULL,NULL),
	(421,'Journey','Journey_ Greatest Hits','Rock','Download',NULL,NULL),
	(422,'Bob Forrest','Modern Folk and Blues Wednesday','Blues','Download',NULL,NULL),
	(423,'Rita Coolidge','Live At The Fillmore East_1970','Country','download',NULL,NULL),
	(424,'Rita Coolidge','Delta Lady _ The Anthology','Country','CD',NULL,NULL),
	(425,'Booker T. Jones','Just a Friend [feat. Biz Markie, Matt Berninger, and Sharon Jones] - Single','Rock','Download',NULL,NULL),
	(426,'James Morrison','Undiscovered','Rock','CD',NULL,NULL),
	(427,'Joan Baez','Noel','Folk','Vinyl',NULL,NULL),
	(428,'Joan Baez','Gulf Winds(8_29_2004 1_30_11 PM)','Folk','Vinyl',NULL,NULL),
	(429,'Joan Baez','1st 10 years','Folk','Vinyl',NULL,NULL),
	(430,'Joan Baez','Blessed Are','Folk','Vinyl',NULL,NULL),
	(431,'Joan Baez','Farewell, Angelina','Folk','Vinyl',NULL,NULL),
	(432,'Joan Baez','Any Day  Now','Folk','Vinyl',NULL,NULL),
	(433,'_ & The Mysterians','The Best Of _ & The Mysterians_ Cameo Parkway 1966-1967','Rock','download',NULL,NULL),
	(434,'_ & The Mysterians','Cameo Parkway_ The Best of _ & the Mysterians, 1966-1967','Rock','Download',NULL,NULL),
	(435,'Steely Dan','Everything Must Go','Rock','Download',NULL,NULL),
	(436,'Steely Dan','A Decade of Steely Dan (Remastered)','Rock','Download',NULL,NULL),
	(437,'Van Morrison','Moondance','Rock','Download',NULL,NULL),
	(438,'Van Morrison','Van Morrison - The Movie Hits','Rock','Download',NULL,NULL),
	(439,'Van Morrison','Pay the Devil','Rock','Download',NULL,NULL),
	(440,'Van Morrison','Born To Sing_ No Plan B','Rock','download',NULL,NULL),
	(441,'Van Morrison','The Movie Hits','Rock','Download',NULL,NULL),
	(442,'Van Morrison','The Best of Van Morrison, Vol. 3','Rock','Download',NULL,NULL),
	(443,'Van Morrison','Blowin'' Your Mind!','Rock','Download',NULL,NULL),
	(444,'A Fielder Boston Pops','The Blue Danube','Classical','Download',NULL,NULL),
	(445,'Pat Metheny','One Quiet Night','Jazz','CD',NULL,NULL),
	(446,'Pat Metheny','80_81','Jazz','Vinyl',NULL,NULL),
	(447,'Pat Metheny','Orchestrion','Jazz','CD',NULL,NULL),
	(448,'Dropkick Murphys','The Gang''s All Here','Rock','Download',NULL,NULL),
	(449,'Dropkick Murphys','The Singles Collection, Vol. 2','Rock','Download',NULL,NULL),
	(450,'Dropkick Murphys','Tessie - EP','Rock','Download',NULL,NULL),
	(451,'Dropkick Murphys','Blackout','Rock','Download',NULL,NULL),
	(452,'Dropkick Murphys','The Warrior''s Code','Rock','Download',NULL,NULL),
	(453,'Dropkick Murphys','Dropkick Murphys_ The Singles Collection, Vol. 1 - 1996-1997','Rock','Download',NULL,NULL),
	(454,'Dropkick Murphys','Live On St.Patrick''s Day','Rock','Download',NULL,NULL),
	(455,'Dropkick Murphys','Sing Loud, Sing Proud!','Rock','Download',NULL,NULL),
	(456,'Dropkick Murphys','The Meanest of Times (Deluxe Edition)','Rock','Download',NULL,NULL),
	(457,'Dropkick Murphys','Dropkick Murphys _ the Business Split Release_ Mob Mentality','Rock','Download',NULL,NULL),
	(458,'Dropkick Murphys','Do or Die','Rock','Download',NULL,NULL),
	(459,'Judy Collins','Both Sides Now_ The Very Best Of','Folk','CD',NULL,NULL),
	(460,'Judy Collins','Judy Collins','Folk','Vinyl',NULL,NULL),
	(461,'Judy Collins','Both Sides Now - The Very Best Of [Disc 2]','Folk','CD',NULL,NULL),
	(462,'Linda Ronstadt','Don''t Cry Now','Country','CD',NULL,NULL),
	(463,'Linda Ronstadt','Just One Look_ Classic Linda Ronstadt','Country','CD',NULL,NULL),
	(464,'Linda Ronstadt','Simple Dreams','Country','CD',NULL,NULL),
	(465,'Linda Ronstadt','Heart Like A Wheel','Country','Vinyl',NULL,NULL),
	(466,'Noam Chomsky','On State Sponsored Terrorism','Talk','Download',NULL,NULL),
	(467,'Prairie Flyer','Just an Old Dog','Country','Download',NULL,NULL),
	(468,'The Chi-Lites','The Chi-Lites_ 20 Greatest Hits','Soul','Download',NULL,NULL),
	(469,'Canned Heat','The Best of Canned Heat','Rock','Download',NULL,NULL),
	(470,'Big Brother & the Holding Company_Janis Joplin','Janis Joplin''s Greatest Hits [10 Tracks]','Rock','CD',NULL,NULL),
	(471,'The Pointer Sisters','Breakout','Rock','Vinyl',NULL,NULL),
	(472,'Dolly Parton','Travelin'' Thru - Single','Country','Download',NULL,NULL),
	(473,'Angele Dubeau & La Pieta','Infernal Violins','Classical','Download',NULL,NULL),
	(474,'Waylon Jennings & Willie Nelson','Waylon & Willie (Remastered)','Country','Download',NULL,NULL),
	(475,'Bobby Rydell','Rock Masters_ Bobby Rydell','Rock','Download',NULL,NULL),
	(476,'Ace Frehley','Ace Frehley','Rock','CD',NULL,NULL),
	(477,'Lori McKenna','Bittertown','Country','Download',NULL,NULL),
	(478,'Jerry Lee Lewis','I Am What I Am','RockaBilly','Download',NULL,NULL),
	(479,'Jerry Lee Lewis','Jerry Lee''s Greatest','RockaBilly','Download',NULL,NULL),
	(480,'Grand Funk Railroad','Grand Funk Railroad Greatest Hits','Rock','Download',NULL,NULL),
	(481,'The Belle Brigade','Where Not to Look for Freedom - Single','Rock','Download',NULL,NULL),
	(482,'Joe Louis Walker','J.L.W_','Jazz','CD',NULL,NULL),
	(483,'Bill Haley & His Comets','20th Century Masters - The Millennium Collection_ Best of Bill Haley & His Comets','RockaBilly','Download',NULL,NULL),
	(484,'Loggins And Messina','Loggins And Messina','Rock','Download',NULL,NULL),
	(485,'The Wailin'' Jennys','Firecracker','Folk','Download',NULL,NULL),
	(486,'The Wailin'' Jennys','40 Days','Folk','Download',NULL,NULL),
	(487,'Leo Sayer','Leo Sayer','Pop','Vinyl',NULL,NULL),
	(488,'Chuck Berry','The Best of Chuck Berry','Rock','Vinyl',NULL,NULL),
	(489,'Donovan','Sunshine Superman','Rock','Download',NULL,NULL),
	(490,'Sting & The Police','The Very Best of Sting & The Police','Rock','Download',NULL,NULL),
	(491,'Jan & Dean','The Best of Jan & Dean (Re-recorded Version)','Rock','Download',NULL,NULL),
	(492,'Jan & Dean','The Best of Jan & Dean (Re-Recorded Versions)','Rock','Download',NULL,NULL),
	(493,'Savoy Brown','Unknown Album','Blues','download',NULL,NULL),
	(494,'Savoy Brown','Hellbound Train','Blues','Download',NULL,NULL),
	(495,'Savoy Brown','Boogie Brothers','Blues','download',NULL,NULL),
	(496,'Savoy Brown','A Step Further','Blues','Download',NULL,NULL),
	(497,'Savoy Brown','The Savoy Brown Collection - Featuring Kim Simmonds','Blues','Download',NULL,NULL),
	(498,'Savoy Brown','Looking In','Blues','Download',NULL,NULL),
	(499,'Nirvana','Incesticide','Rock','CD',NULL,NULL),
	(500,'Tony Bennett','Snowfall - The Tony Bennett Christmas Album','Pop','Download',NULL,NULL),
	(501,'Stevie Ray Vaughan','Martin Scorsese Presents_ Stevie Ray Vaughan','Blues','Download',NULL,NULL),
	(502,'Chad & Jeremy','60''s Jukebox Hits - Vol. 3','Rock','Download',NULL,NULL),
	(503,'Chad & Jeremy','The Sunshine Collection','Rock','Download',NULL,NULL),
	(504,'Matt Nathanson','Faster - Single','Rock','Download',NULL,NULL),
	(505,'Alison Krauss & Union Station','Paper Airplane','Country','CD',NULL,NULL),
	(506,'Alison Krauss & Union Station','New Favorite','Country','Download',NULL,NULL),
	(507,'Charles Dutoit, Kyung Wha Chung & Philharmonia Orchestra','Saint-Saens_ Danse Macabre','Classical','Download',NULL,NULL),
	(508,'Devin Duval','Fordham Session','Jazz','CD',NULL,NULL),
	(509,'Devin Duval','Senior Recital','Jazz','CD',NULL,NULL),
	(510,'Devin Duval','Audition Tape','Jazz','CD',NULL,NULL),
	(511,'Devin Duval','Devin Duval Album (7_14_2008 9_22_53 PM)','Jazz','CD',NULL,NULL),
	(512,'Crooked Still','Shaken By A Low Sound','BlueGrass','CD',NULL,NULL),
	(513,'The Quintet','V.S.O.P','Jazz','Download',NULL,NULL),
	(514,'Boston','Boston_ Greatest Hits','Rock','Download',NULL,NULL),
	(515,'Boston','Life, Love & Hope','Rock','CD',NULL,NULL),
	(516,'Sarah McLachlan','Wintersong','Pop','Download',NULL,NULL),
	(517,'Norah Jones','Come Away With Me','Pop','CD',NULL,NULL),
	(518,'Branford Marsalis & Orpheus Chamber Orchestra','Creation','Classical','Download',NULL,NULL),
	(519,'S. Carey','All We Grow (Bonus Track Version)','Pop','Download',NULL,NULL),
	(520,'Stray Birds','The Stray Birds','Country','CD',NULL,NULL),
	(521,'Peter, Paul & Mary','See What Tomorrow Brings','Folk','Download',NULL,NULL),
	(522,'Buddy Tate','Jumping On the West Coast','Jazz','Download',NULL,NULL),
	(523,'Freddy Fender','Golden Legends_ Freddy Fender Live','TexMex','Download',NULL,NULL),
	(524,'The Troggs','Wild Thing','Rock','Download',NULL,NULL),
	(525,'City and Colour','Fragile Bird - Single','Rock','Download',NULL,NULL),
	(526,'Strawberry Alarm Clock','Incense & Peppermints','Rock','Download',NULL,NULL),
	(527,'Tina Turner','Private Dancer','Rock','Vinyl',NULL,NULL),
	(528,'U2','U218 Singles (Deluxe Version)','Rock','Download',NULL,NULL),
	(529,'U2','Songs of Innocence','Rock','Download',NULL,NULL),
	(530,'Texas Tornados','Zone of Our Own','TexMex','Download',NULL,NULL),
	(531,'Texas Tornados','Live from Austin, TX_ Texas Tornados','TexMex','Download',NULL,NULL),
	(532,'Jerry Gonzalez & The Fort Apache Band','Rumba Para Monk','Rock','Download',NULL,NULL),
	(533,'Johnny Mathis','Merry Christmas','Pop','Download',NULL,NULL),
	(534,'Steve Miller Band','Greatest Hits_ 1974-1978','Rock','Download',NULL,NULL),
	(535,'Peter Bjorn and John','Eyes - Single','Pop','Download',NULL,NULL),
	(536,'The Pretenders','Alone','Rock','CD',NULL,NULL),
	(537,'Eagles','Their Greatest Hits','Rock','download',NULL,NULL),
	(538,'Eagles','One of These Nights','Rock','Download',NULL,NULL),
	(539,'Eagles','Hotel California','Rock','Download',NULL,NULL),
	(540,'Eagles','Eagles','Rock','Download',NULL,NULL),
	(541,'Eagles','On The Border','Rock','CD',NULL,NULL),
	(542,'Eagles','Long Road Out Of Eden [Disc 2]','Rock','Download',NULL,NULL),
	(543,'Eagles','Long Road Out Of Eden [Disc 1]','Rock','Download',NULL,NULL),
	(544,'Eagles','Hell Freezes Over','Rock','CD',NULL,NULL),
	(545,'Michael Martin Murphey','Cowboy Songs 3','Country','CD',NULL,NULL),
	(546,'Madeleine Peyroux','The Blue Room','Jazz','Download',NULL,NULL),
	(547,'The Jazz Crusaders','Free As The Wind','Jazz','Vinyl',NULL,NULL),
	(548,'The Jazz Crusaders','The Best Of The Jazz Crusaders 1961 - 1965','Jazz','Download',NULL,NULL),
	(549,'The Jazz Crusaders','Southern Comfort','Jazz','Vinyl',NULL,NULL),
	(550,'The Jazz Crusaders','Crusaders 1','Jazz','Vinyl',NULL,NULL),
	(551,'The Jazz Crusaders','Live at the Lighthouse ''66','Jazz','Download',NULL,NULL),
	(552,'The Jazz Crusaders','The Best of the Jazz Crusaders','Jazz','Download',NULL,NULL),
	(553,'Mountain Heart','Road That Never Ends_ The Live Album','BlueGrass','CD',NULL,NULL),
	(554,'Harry Nilsson','Personal Best - The Harry Nilsson Anthology','Rock','Download',NULL,NULL),
	(555,'Harry Nilsson','Nilsson Schmilsson (Remastered)','Rock','Download',NULL,NULL),
	(556,'Roy Orbison','For the Lonely_ 18 Greatest Hits','Rock','Download',NULL,NULL),
	(557,'Armik','Serenata','Pop','Download',NULL,NULL),
	(558,'The Surfaris','The Sunshine Collection','Rock','Download',NULL,NULL),
	(559,'Eilen Jewell','Letters from Sinners & Strangers','Country','Download',NULL,NULL),
	(560,'Eilen Jewell','Sea Of Tears','Country','CD',NULL,NULL),
	(561,'Jimmy Buffet','Livign And Dying In Three Quarter Time','Country','Vinyl',NULL,NULL),
	(562,'Jimmy Buffet','Son Of A Sailor','Country','Vinyl',NULL,NULL),
	(563,'Jimmy Buffet','Changes In Latitudes-Havana Day Dreamin','Country','Vinyl',NULL,NULL),
	(564,'Art Garfunkel','Garfunkel','Folk','CD',NULL,NULL),
	(565,'Wrabel','Sideways - Single','Pop','Download',NULL,NULL),
	(566,'The Paul Butterfield Blues Band','The Butterfield Blues Band Live','Blues','Vinyl',NULL,NULL),
	(567,'The Paul Butterfield Blues Band','Butterfield Blues Band Live','Blues','Vinyl',NULL,NULL),
	(568,'The Paul Butterfield Blues Band','East-West','Blues','Vinyl',NULL,NULL),
	(569,'The Paul Butterfield Blues Band','The Paul Butterfield Blues Band','Blues','Vinyl',NULL,NULL),
	(570,'Compilations','Jazz Selects','Jazz','CD',NULL,NULL),
	(571,'Compilations','The Art Of McCartney [Disc 1]','Rock','download',NULL,NULL),
	(572,'Compilations','Easy Rider (Soundtrack from the Motion Picture) [Deluxe Edition]','Rock','Download',NULL,NULL),
	(573,'Compilations','JACO Original Soundtrack','Jazz','CD',NULL,NULL),
	(574,'Compilations','The Art Of McCartney [Disc 2]','Rock','download',NULL,NULL),
	(575,'Compilations','Strawberry Letter 23_ The Very Best of the Brothers Johnson','Rock','Download',NULL,NULL),
	(576,'Compilations','50''s Rock','Rock','Tape',NULL,NULL),
	(577,'Compilations','I''m Not There [Disc 1]','Folk','CD',NULL,NULL),
	(578,'Compilations','Gypsy Soul New Flamenco','Rock','download',NULL,NULL),
	(579,'Compilations','I''m Not There [Disc 2]','Folk','CD',NULL,NULL),
	(580,'Compilations','Both Sides Now_ The Very Best Of','Folk','CD',NULL,NULL),
	(581,'Compilations','Delta Lady The Anthology','Rock','download',NULL,NULL),
	(582,'Compilations','The Departed','Rock','CD',NULL,NULL),
	(583,'Compilations','Blues Selects','Blues','CD',NULL,NULL),
	(584,'Compilations','20th Century Rocks_ 60''s Rock Bands - Wild Thing (Re-Recorded Versions)','Rock','download',NULL,NULL),
	(585,'Compilations','Mambo Bounce','Jazz','CD',NULL,NULL),
	(586,'Compilations','Both Sides Now - The Very Best Of [Disc 2]','Folk','CD',NULL,NULL),
	(587,'Compilations','Masked & Anonymous','Folk','CD',NULL,NULL),
	(588,'Compilations','Rat Pack_ Members Edition [Live]','Easy Listening','CD',NULL,NULL),
	(589,'Compilations','The Anthology','Rock','Download',NULL,NULL),
	(590,'Compilations','Delta Lady_ The Rita Coolidge Anthology [Disc 2]','Country','CD',NULL,NULL),
	(591,'Compilations','Duets','Rock','CD',NULL,NULL),
	(592,'Compilations','The Music Inside_ A Collaboration Dedicated To Waylon Jennings, Volume II','Country','CD',NULL,NULL),
	(593,'Compilations','The Music Inside - A Collaboration Dedicated to Waylon Jennings, Vol. 1','Country','CD',NULL,NULL),
	(594,'Compilations','4 John Paul George Ringo - EP','Rock','Download',NULL,NULL),
	(595,'Compilations','Singin'' With Emmylou Volume 1 (P) 2000','Country','CD',NULL,NULL),
	(596,'Electric Light Orchestra','Out Of The Blue','Rock','CD',NULL,NULL),
	(597,'Electric Light Orchestra','Face The Music','Rock','Vinyl',NULL,NULL),
	(598,'Electric Light Orchestra','Discovery','Rock','Vinyl',NULL,NULL),
	(599,'Electric Light Orchestra','Eldorado','Rock','Vinyl',NULL,NULL),
	(600,'The Youngbloods','Get Together_ The Essential Youngbloods','Rock','Download',NULL,NULL),
	(601,'Generationals','Trust - EP','Pop','Download',NULL,NULL),
	(602,'Pink Floyd','Dark Side of the Moon','Rock','Download',NULL,NULL),
	(603,'Pink Floyd','More_ Original Motion Picture Soundtrack','Rock','download',NULL,NULL),
	(604,'Pink Floyd','The Wall [Disc 1]','Rock','Download',NULL,NULL),
	(605,'Pink Floyd','The Wall [Disc 2]','Rock','Download',NULL,NULL),
	(606,'Ricketic','Steelers Wheel - Stuck in the Middle (Ricketic Edit) - Single','Rock','Download',NULL,NULL),
	(607,'Percy Sledge','More Solid Gold 60s Volume 2','Blues','Download',NULL,NULL),
	(608,'Lovin Spoonful','Lovin Spoonful Anthology','Rock','CD',NULL,NULL),
	(609,'Bachman-Turner Overdrive','Not Fragile','Rock','Vinyl','Bachman-Turner_Overdrive_-_Not_Fragile.jpg',3),
	(610,'Bachman-Turner Overdrive','The Definitive Collection Bachman-Turner Overdrive','Rock','Download',NULL,NULL),
	(611,'Edgar Winter','The Best of Edgar Winter','Rock','Download',NULL,NULL),
	(612,'Iron & Wine','Tree By The River - Single','Pop','Download',NULL,NULL),
	(613,'War','The World Is A Ghetto','Rock','download',NULL,NULL),
	(614,'War','Platinum Jazz','Rock','Vinyl',NULL,NULL),
	(615,'War','Best of War','Rock','Download',NULL,NULL),
	(616,'War','The Very Best of War','Rock','Download',NULL,NULL),
	(617,'Alvin Lee','Live at Rockpalast (Remastered)','Blues','Download',NULL,NULL),
	(618,'Alvin Lee','In Tennessee','Blues','Download',NULL,NULL),
	(619,'Alvin Lee','Keep on Rockin''','Blues','Download',NULL,NULL),
	(620,'Alvin Lee','Live In Vienna','Blues','Download',NULL,NULL),
	(621,'Eddie Vedder','Longing to Belong - Single','Rock','Download',NULL,NULL),
	(622,'Linda Ronstadt & Emmylou Harris','Western Wall_ The Tucson Sessions','Country','download',NULL,NULL),
	(623,'The Searchers','The Very Best of... The Searchers','Rock','Download',NULL,NULL),
	(624,'Dire Straits','Making Movies','Rock','Vinyl',NULL,NULL),
	(625,'Dire Straits','Sultans of Swing - The Very Best of Dire Straits','Rock','Download',NULL,NULL),
	(626,'Dire Straits','Live in Concert','Rock','download',NULL,NULL),
	(627,'Dire Straits','Brothers in Arms','Rock','CD',NULL,NULL),
	(628,'Miles Davis Quintet','Workin'' With The Miles Davis Quintet','Jazz','Vinyl',NULL,NULL),
	(629,'Ben Harper','Rock ''N'' Roll Is Free - Single','Rock','Download',NULL,NULL),
	(630,'Waylon Jennings','Love Of The Common People','Country','Download',NULL,NULL),
	(631,'Waylon Jennings','What Goes Around Comes Around','Country','Vinyl',NULL,NULL),
	(632,'Waylon Jennings','Right For The Time','Country','Download',NULL,NULL),
	(633,'Waylon Jennings','The Essential Waylon Jennings','Country','Download',NULL,NULL),
	(634,'Waylon Jennings','Honky Tonk Heroes','Country','CD',NULL,NULL),
	(635,'Joe Walsh','Joe Walsh''s Greatest Hits_ Little Did He Know.._','Rock','Download',NULL,NULL),
	(636,'Roberta Flack & Donny Hathaway','Roberta Flack & Donny Hathaway','R&B','Download',NULL,NULL),
	(637,'Motorhead','Bad Magic','Rock','CD',NULL,NULL),
	(638,'Martha Reeves & The Vandellas','The Ultimate Collection_ Martha Reeves & The Vandellas','Soul','Download',NULL,NULL),
	(639,'The Zombies','Odessey and Oracle','Rock','Download',NULL,NULL),
	(640,'The Four Tops','50th Anniversary Anthology [Disc 2]','R&B','CD',NULL,NULL),
	(641,'The Four Tops','50th Anniversary Anthology [Disc 1]','R&B','CD',NULL,NULL),
	(642,'The Dave Clark Five','The Dave Clark Five_ The Hits (Bonus Track Version)','Rock','Download',NULL,NULL),
	(643,'The Knack','My Sharona _ Good Girls Don''t (Re-Recorded) - Single','Rock','Download',NULL,NULL),
	(644,'The Coasters','The Very Best Of The Coasters','Soul','CD',NULL,NULL),
	(645,'Blood Sweat & Tears','No Sweat','Rock','Vinyl',NULL,NULL),
	(646,'Blood Sweat & Tears','New Blood','Rock','Vinyl',NULL,NULL),
	(647,'Blood Sweat & Tears','Blood Sweat & Tears 3','Rock','Vinyl',NULL,NULL),
	(648,'Johnny Rivers','Greatest Hits Johnny Rivers','Rock','Download',NULL,NULL),
	(649,'Johnny Rivers','Johnny Rivers_ Greatest Hits','Rock','Download',NULL,NULL),
	(650,'The Rolling Stones','Singles Collection_ The London Years [Disc 3]','Rock','CD',NULL,NULL),
	(651,'The Rolling Stones','Singles Collection_ The London Years [Disc 1]','Rock','CD',NULL,NULL),
	(652,'The Rolling Stones','Singles Collection_ The London Years [Disc 2]','Rock','CD',NULL,NULL),
	(653,'The Young Rascals','Time Peace_ The Rascals'' Greatest Hits','Rock','Download',NULL,NULL),
	(654,'The Young Rascals','Essentials_ The Rascals','Rock','Download',NULL,NULL),
	(655,'The Young Rascals','The Young Rascals','Rock','Download',NULL,NULL),
	(656,'The Young Rascals','Groovin''','Rock','Download',NULL,NULL),
	(657,'Michael Brecker','Michael Brecker','Jazz','Vinyl',NULL,NULL),
	(658,'Michael Brecker','CityScape','Jazz','Vinyl',NULL,NULL),
	(659,'Jose Feliciano','Fireworks','Pop','Download',NULL,NULL),
	(660,'Jose Feliciano','Feliz Navidad','Pop','Vinyl',NULL,NULL),
	(661,'Them','Them Featuring Van Morrison','Rock','Download',NULL,NULL),
	(662,'Elvis Presley','The Essential Elvis Presley (Remastered)','Rock','Download',NULL,NULL),
	(663,'Elvis Presley','Elvis''s Christmas Album','Rock','Vinyl',NULL,NULL),
	(664,'Jimi Hendrix','Are You Experienced_','Rock','CD',NULL,NULL),
	(665,'Jimi Hendrix','South Saturn Delta','Rock','Vinyl',NULL,NULL),
	(666,'Jimi Hendrix','Rainbow Bridge','Rock','Vinyl',NULL,NULL),
	(667,'Florida Georgia Line','Anything Goes','Country','CD',NULL,NULL),
	(668,'Iron Butterfly & Vanilla Fudge','Iron Butterfly Hits','Rock','Download',NULL,NULL),
	(669,'Waylon and Willie','Waylon and Willie','Country','Vinyl',NULL,NULL),
	(670,'Johnny Nash','Radio Hits of the ''70s','Rock','Download',NULL,NULL),
	(671,'George Baker','Hollands Glorie','Rock','Download',NULL,NULL),
	(672,'The Beatles','Sgt Peppers Lonely Hearts Club Band','Rock','Vinyl',NULL,NULL),
	(673,'The Beatles','Beatles For Sale','Rock','CD',NULL,NULL),
	(674,'The Beatles','Beatles IV','Rock','Vinyl',NULL,NULL),
	(675,'The Beatles','Beatles''65','Rock','Vinyl',NULL,NULL),
	(676,'The Beatles','The Beatles'' Second Album','Rock','Vinyl',NULL,NULL),
	(677,'The Beatles','Meet The Beatles','Rock','Vinyl',NULL,NULL),
	(678,'The Beatles','Let It Be','Rock','Download',NULL,NULL),
	(679,'The Beatles','Yesterday and Today','Rock','Vinyl',NULL,NULL),
	(680,'The Beatles','Hard Days Night','Rock','Vinyl',NULL,NULL),
	(681,'The Beatles','Rubber Soul (North American)','Rock','Vinyl',NULL,NULL),
	(682,'The Beatles','The Beatles Songs Pictures And Stories','Rock','Vinyl',NULL,NULL),
	(683,'The Beatles','Something New','Rock','Vinyl',NULL,NULL),
	(684,'The Beatles','Magical Mystery Tour','Rock','Vinyl',NULL,NULL),
	(685,'The Beatles','Beatles Again(Hey Jude)','Rock','Vinyl',NULL,NULL),
	(686,'The Beatles','Beatles 62-66','Rock','Vinyl',NULL,NULL),
	(687,'The Beatles','Rubber Soul','Rock','Vinyl',NULL,NULL),
	(688,'The Beatles','Abbey Road','Rock','CD',NULL,NULL),
	(689,'The Beatles','Help','Rock','Vinyl',NULL,NULL),
	(690,'The Beatles','White Album','Rock','Vinyl',NULL,NULL),
	(691,'Steppenwolf','Best of Steppenwolf_ 20th Century Masters','Rock','Download',NULL,NULL),
	(692,'Bread','The Best Of Bread','Rock','CD',NULL,NULL),
	(693,'18 South','Soulful Southern Roots Music','Blues','Download',NULL,NULL),
	(694,'Radiohead','Amnesiac','Rock','CD',NULL,NULL),
	(695,'Rod Stewart','Driving Music','Rock','Tape','Men_AT_Work_Down_Under_australia_single.jpg',4),
	(696,'John Lee Hooker','Live at the Cafe au-Go-Go (and Soledad Prison)','Blues','Download',NULL,NULL),
	(697,'John Lee Hooker','Urban Blues (Bonus Track Version)','Blues','Download',NULL,NULL),
	(698,'Leo Kottke','Leo Kottke-John Fahey-Peter Lang','Pop','Vinyl',NULL,NULL),
	(699,'Parts & Labor','Constant Future','Pop','Download',NULL,NULL),
	(700,'Gillian Welch','Hard Times','Rock','Download',NULL,NULL),
	(701,'The Left Banke','There''s Gonna Be a Storm - The Complete Recordings 1966-1969','Rock','Download',NULL,NULL),
	(702,'Celtic Christmas','Celtic Christmas','Pop','CD',NULL,NULL),
	(703,'Paul McCartney & Wings','Band on the Run','Rock','CD',NULL,NULL),
	(704,'Dr. John','Goin'' Back To New Orleans','Rock','CD',NULL,NULL),
	(705,'Kenny Rogers & The First Edition','Anthology Kenny Rogers & The First Edition','Rock','Download',NULL,NULL),
	(706,'Cream','Fresh Cream','Blues','Vinyl',NULL,NULL),
	(707,'Cream','Goodbye','Blues','CD',NULL,NULL),
	(708,'Cream','Cream','Blues','Download',NULL,NULL),
	(709,'Cream','The Very Best of Cream','Blues','Download',NULL,NULL),
	(710,'Cream','Live Cream Vol 2','Blues','CD',NULL,NULL),
	(711,'Junip','Fields','Pop','Download',NULL,NULL),
	(712,'Beady Eye','The Roller - Single','Pop','Download',NULL,NULL),
	(713,'The Centurions','Bullwinkle Part II','Rock','Download',NULL,NULL),
	(714,'The Tokens','The Lion Sleeps Tonight','Rock','Download',NULL,NULL),
	(715,'Nitty Gritty Dirt Band','Dirt Siver Gold','Rock','Vinyl',NULL,NULL),
	(716,'Oscar Peterson','Night Train','Jazz','Download',NULL,NULL),
	(717,'The Allman Brothers Band','Fillmore East','Rock','Vinyl',NULL,NULL),
	(718,'The Allman Brothers Band','Eat A Peach','Rock','Vinyl',NULL,NULL),
	(719,'The Allman Brothers Band','Brothers And Sisters','Rock','Vinyl',NULL,NULL),
	(720,'The Allman Brothers Band','Beginnings','Rock','Vinyl',NULL,NULL),
	(721,'Bon Jovi','Slippery When Wet','Rock','Download',NULL,NULL),
	(722,'Bon Jovi','Bon Jovi','Rock','CD',NULL,NULL),
	(723,'Booker T. & The MG''s','The Best of Booker T & The MGs','R&B','Download',NULL,NULL),
	(724,'Assassin','Infiltration','Pop','Download',NULL,NULL),
	(725,'Joe Cocker','You Are So Beautiful','Rock','Vinyl',NULL,NULL),
	(726,'Joe Cocker','Joe Cocker''s Greatest Hits','Rock','Vinyl','JoeCocker.jpg',5),
	(727,'Joe Cocker','I Can Stand A Little Rain','Rock','Vinyl',NULL,NULL),
	(728,'The Guess Who','American Woman','Rock','CD',NULL,NULL),
	(729,'The Guess Who','Shakin'' All Over','Rock','Download',NULL,NULL),
	(730,'The Guess Who','Rockin Guess Who','Rock','Vinyl',NULL,NULL),
	(731,'The Guess Who','The Guess Who_ Greatest Hits','Rock','Download',NULL,NULL),
	(732,'The Spencer Davis Group','The Best of the Spencer Davis Group','Rock','Download',NULL,NULL),
	(733,'Mungo Jerry','The Sunshine Collection','Rock','Download',NULL,NULL),
	(734,'Mungo Jerry','The Very Best of Mungo Jerry','Rock','Download',NULL,NULL),
	(735,'The Band','Greatest Hits [Remastered] [UK]','Rock','Download',NULL,NULL),
	(736,'The Band','The Last Waltz [2003 Remaster] Disc 2','Rock','CD',NULL,NULL),
	(737,'The Band','The Last Waltz [2003 Remaster] Disc 1','Rock','CD',NULL,NULL),
	(738,'Bing Crosby','All-Time Christmas Favorites, Vol. 1','Pop','Download',NULL,NULL),
	(739,'The 5th Dimension','The Essential Fifth Dimension','Rock','CD',NULL,NULL),
	(740,'The 5th Dimension','The Essential Fifth Dimension [Disc 1]','Rock','CD',NULL,NULL),
	(741,'The Drifters','Under the Boardwalk','Soul','Download',NULL,NULL),
	(742,'The Drifters','The Essentials_ The Drifters','Soul','Download',NULL,NULL),
	(743,'John Fahey & His Orchestra','Of Rivers and Religion _ After the Ball','Pop','Download',NULL,NULL),
	(744,'Jeff Beck','Loud Hailer','Rock','CD',NULL,NULL),
	(745,'Jeff Beck','Best Of Beck','Rock','CD',NULL,NULL),
	(746,'Jeff Beck','Wired','Rock','Download',NULL,NULL),
	(747,'Playing for Change','Redemption Song - Single','Pop','Download',NULL,NULL),
	(748,'Jimmy Witherspoon','Live At the 1972 Monterey Jazz Festival (feat. Robben Ford)','Jazz','Download',NULL,NULL),
	(749,'Jimmy Witherspoon','The Best Of Jimmy Witherspoon','Jazz','Vinyl',NULL,NULL),
	(750,'Dale Hawkins','Suzie Q & Let''s All Twist','RockaBilly','Download',NULL,NULL),
	(751,'Arcade Fire','The Suburbs','Pop','Download',NULL,NULL),
	(752,'The Mavericks','20th Century Masters - The Millennium Collection_ The Best of the Mavericks','TexMex','Download',NULL,NULL),
	(753,'The Mavericks','Rancho Loco','TexMex','Download',NULL,NULL),
	(754,'The Mavericks','Mono','TexMex','CD',NULL,NULL),
	(755,'Kansas','The Best of Kansas','Rock','Download',NULL,NULL),
	(756,'Kansas','Point of Know Return','Rock','Download',NULL,NULL),
	(757,'Kansas','Vinyl Confessions','Rock','Download',NULL,NULL),
	(758,'Men At Work','Business As Usual','Rock','CD',NULL,NULL),
	(759,'Men At Work','Driving Music','Rock','Tape','Men_AT_Work_Down_Under_australia_single.jpg',4),
	(760,'Branford Marsalis','Renaissance','Jazz','Download',NULL,NULL),
	(761,'Branford Marsalis','Romances For Saxophone','Jazz','Vinyl',NULL,NULL),
	(762,'Yes','The Yes Album','Rock','CD',NULL,NULL),
	(763,'Yes','The Very Best of Yes','Rock','CD',NULL,NULL),
	(764,'The Seeds','The Seeds','Rock','Download',NULL,NULL),
	(765,'Bruce Springsteen','Magic','Rock','CD',NULL,NULL),
	(766,'Bruce Springsteen','Working On A Dream','Rock','Download',NULL,NULL),
	(767,'Bruce Springsteen','Born To Run','Rock','Vinyl',NULL,NULL),
	(768,'Bruce Springsteen','Nebraska','Rock','CD',NULL,NULL),
	(769,'Bruce Springsteen','High Hopes','Rock','CD',NULL,NULL),
	(770,'Bruce Springsteen','Born In The USA','Rock','Vinyl',NULL,NULL),
	(771,'Foghat','Fool for the City','Rock','Download',NULL,NULL),
	(772,'Foghat','Drivin'' Wheels_ Best Of 1972-1982 [Disc 1]','Rock','CD',NULL,NULL),
	(773,'Foghat','Drivin'' Wheels_ Best Of 1972-1982 [Disc 2]','Rock','CD',NULL,NULL),
	(774,'Eldorado','Suitcase','TexMex','Download',NULL,NULL),
	(775,'The Doors','Best of the Doors','Rock','Vinyl',NULL,NULL),
	(776,'The Doors','The Future Starts Here_ The Essential Doors Hits','Rock','Download',NULL,NULL),
	(777,'The Doors','The Very Best of the Doors','Rock','Download',NULL,NULL),
	(778,'The Doors','The Doors','Rock','Download',NULL,NULL),
	(779,'David Bromberg Band','Midnight On the Water David Bromberg Band','Rock','Download',NULL,NULL),
	(780,'David Allan Coe','The Essential David Allan Coe','Country','CD',NULL,NULL),
	(781,'David Allan Coe','20 All-Time Greatest Hits','Rock','Download',NULL,NULL),
	(782,'The Traveling Wilburys','The Traveling Wilburys, Vol. 1','Rock','CD',NULL,NULL),
	(783,'Neil Sedaka','Love Songs_ Neil Sedaka','Pop','Download',NULL,NULL),
	(784,'James Brown','The 50th Anniversary Collection [Disc 2]','R&B','CD',NULL,NULL),
	(785,'James Brown','The 50th Anniversary Collection [Disc 1]','R&B','CD',NULL,NULL),
	(786,'Robert Plant & Alison Krauss','Raising Sand','Country','Download',NULL,NULL),
	(787,'Dave Mason','Split Coconut','Rock','Download',NULL,NULL),
	(788,'Dave Mason','Alone Together','Rock','Tape',NULL,NULL),
	(789,'Dave Mason','Long Lost Friend - The Best of Dave Mason','Rock','Download',NULL,NULL),
	(790,'John Lennon','Rock ''N'' Roll','Rock','Vinyl',NULL,NULL),
	(791,'John Lennon','Working Class Hero The Definitive Lennon','Rock','Download',NULL,NULL),
	(792,'John Lennon','Lennon Legend The Very Best of John Lennon','Rock','CD',NULL,NULL),
	(793,'John Lennon','Imagine','Rock','Vinyl',NULL,NULL),
	(794,'Marty Robbins','Marty Robbins'' All-Time Greatest Hits','Country','Download',NULL,NULL),
	(795,'Marty Robbins','The Essential Marty Robbins (1951-1982)','Country','Download',NULL,NULL),
	(796,'Marty Robbins','Marty Robbins_ More Greatest Hits','Country','Download',NULL,NULL),
	(797,'Marty Robbins','Gunfighter Ballads and Trail Songs','Country','CD',NULL,NULL),
	(798,'James Gang','James Gang_ Greatest Hits','Rock','Download',NULL,NULL),
	(799,'James Gang','16 Greatest Hits','Rock','Vinyl',NULL,NULL),
	(800,'Joe Henderson','The Elements','Jazz','Download',NULL,NULL),
	(801,'Billy Joel','52nd Street','Rock','Vinyl',NULL,NULL),
	(802,'Pete Segear Arlo Guthrie','Together In Concert','Rock','download',NULL,NULL),
	(803,'Johnny Winter','Roots','Blues','CD',NULL,NULL),
	(804,'Johnny Winter','Step Back','Blues','CD',NULL,NULL),
	(805,'Johnny Winter','The Best of Johnny Winter','Blues','CD',NULL,NULL),
	(806,'Johnny Winter','Still Alive and Well','Blues','CD',NULL,NULL),
	(807,'Johnny Winter','I''m a Bluesman','Blues','CD',NULL,NULL),
	(808,'Johnny Winter','The Progressive Blues Experiment','Blues','CD',NULL,NULL),
	(809,'Johnny Winter','2nd Winter','Blues','Vinyl',NULL,NULL),
	(810,'The Shadows','The Platinum Collection','Rock','Download',NULL,NULL),
	(811,'The Shadows','The Final Tour (Live)','Rock','Download',NULL,NULL),
	(812,'The Handsome Family','Down to the Promised Land - Five Years of Bloodshot Records','Country','Download',NULL,NULL),
	(813,'The Handsome Family','In the Air','Country','Download',NULL,NULL),
	(814,'The Handsome Family','Scattered','Country','Download',NULL,NULL),
	(815,'The Handsome Family','Singing Bones','Country','Download',NULL,NULL),
	(816,'Janis Joplin','Super Hits Janis Joplin','Rock','CD',NULL,NULL),
	(817,'Janis Joplin','Pearl','Rock','Download',NULL,NULL),
	(818,'Less McCann and Eddie Harris','Swiss Movement','Jazz','Vinyl',NULL,NULL),
	(819,'Seals & Crofts','Seals & Crofts Greatist Hits','Rock','CD',NULL,NULL),
	(820,'Charlie Rich','Every Time You Touch Me','Country','Vinyl',NULL,NULL),
	(821,'Charlie Rich','Best of Charlie Rich','Country','Vinyl',NULL,NULL),
	(822,'The Police','The Police (Remastered)','Rock','Download',NULL,NULL),
	(823,'The Kingsmen','The Best of The Kingsmen','Rock','Download',NULL,NULL),
	(824,'The Kingsmen','Louie Louie_ The Very Best of The Kingsmen','Rock','Download',NULL,NULL),
	(825,'Steve Goodman','Jessies Jig-Words We Can Dance To','Folk','Download',NULL,NULL),
	(826,'Steve Goodman','Steve Goodman','Folk','Download',NULL,NULL),
	(827,'Procol Harum','Live At the Union Chapel','Rock','Download',NULL,NULL),
	(828,'Procol Harum','Procol Harum Greatest Hits','Rock','Download',NULL,NULL),
	(829,'Alfred Hause And His Vienna Waltz Country Ballroom Orchestra','The Blue Danube Waltz','Classical','Download',NULL,NULL),
	(830,'John Mayall','Drivin'' On_ The ABC Years (1975-1982) Disc 2','Blues','CD',NULL,NULL),
	(831,'John Mayall','Find A Way To Care','Blues','CD',NULL,NULL),
	(832,'John Mayall','Back to the Roots Disc 2','Blues','CD',NULL,NULL),
	(833,'John Mayall','Drivin'' On_ The ABC Years (1975-1982) Disc 1','Blues','CD',NULL,NULL),
	(834,'John Mayall','The Turning Point','Blues','download',NULL,NULL),
	(835,'John Mayall','Back to the Roots Disc 1','Blues','CD',NULL,NULL),
	(836,'Pete Townshend & Ronnie Lane','Rough Mix','Rock','Vinyl',NULL,NULL),
	(837,'Jesse Thomas','You I Want (Radio Edit) - Single','Pop','Download',NULL,NULL),
	(838,'Don McLean','Rearview Mirror','Rock','Download',NULL,NULL),
	(839,'Don McLean','American Pie','Rock','Download',NULL,NULL),
	(840,'Fleetwood Mac','Rumours','Rock','Vinyl',NULL,NULL),
	(841,'Fleetwood Mac','Say You Will','Rock','CD',NULL,NULL),
	(842,'Fleetwood Mac','Peter Green''s Fleetwood Mac (Remastered)','Rock','Download',NULL,NULL),
	(843,'Fleetwood Mac','Fleetwood Mac Hits','Rock','Download',NULL,NULL),
	(844,'Fleetwood Mac','The Vaudeville Years of Fleetwood Mac - 1968-1970','Rock','Download',NULL,NULL),
	(845,'The Mamas & The Papas','The Mamas & The Papas Greatest Hits','Folk','Download',NULL,NULL),
	(846,'Three Dog Night','Best Of Three Dog Night','Rock','Vinyl',NULL,NULL),
	(847,'The Beach Boys','The Beach Boys 20 Golden Greats','Rock','Vinyl','Beach Boys 20 Greatest.jpg',35),
	(848,'The Beach Boys','The Beach Boys 15 Big Ones','Rock','CD','BeachBoys_15BigOnesCover.jpg',1),
	(849,'Chick Corea','Expressions','Jazz','CD',NULL,NULL),
	(850,'Mark Lanegan','More Oar_ A Tribute to the Skip Spence Album','Folk','Download',NULL,NULL),
	(851,'Walela','Walela','Folk','CD',NULL,NULL),
	(852,'Frank Sinatra','The Reprise Collection [Disc 3]','Pop','CD',NULL,NULL),
	(853,'Frank Sinatra','Reprise Collection [Disc 4]','Pop','CD',NULL,NULL),
	(854,'Frank Sinatra','The Reprise Collection [Disc 1]','Pop','CD',NULL,NULL),
	(855,'Frank Sinatra','The Reprise Collection [Disc 2]','Pop','CD',NULL,NULL),
	(856,'The Box Tops','Tear Off!','Soul','Download',NULL,NULL),
	(857,'The Box Tops','The Letter _ Neon Rainbow','Soul','Download',NULL,NULL),
	(858,'Genesis','Genesis','Rock','CD',NULL,NULL),
	(859,'Stray Cats','Built For Speed','Rock','CD',NULL,NULL),
	(860,'Say Hi','Um, Uh Oh (Bonus Track Version)','Pop','Download',NULL,NULL),
	(861,'Ottmar Liebert_Luna Negra','Euphoria','Pop','CD',NULL,NULL),
	(862,'John Coltrane & Johnny Hartman','John Coltrane & Johnny Hartman','Jazz','Vinyl',NULL,NULL),
	(863,'Little River Band','Rearranged','Rock','Download',NULL,NULL),
	(864,'Tower of Power','The Very Best of Tower of Power_ The Warner Years','R&B','CD',NULL,NULL),
	(865,'Tower of Power','Back to Oakland','R&B','CD',NULL,NULL),
	(866,'Tower of Power','Monster on a Leash','R&B','CD',NULL,NULL),
	(867,'Neko Case','Furnace Room Lullaby','Rock','CD',NULL,NULL),
	(868,'Neko Case','Middle Cyclone','Rock','CD',NULL,NULL),
	(869,'Neko Case','Blacklisted','Rock','CD',NULL,NULL),
	(870,'Diego Garcia','You Were Never There - Single','Pop','Download',NULL,NULL),
	(871,'Alice Cooper','Alice Cooper''s Greatest Hits','Rock','Download',NULL,NULL),
	(872,'Alice Cooper','The Last Temptation','Rock','CD',NULL,NULL),
	(873,'Hair','Hair','Rock','Vinyl',NULL,NULL),
	(874,'Thelonious Monk','Criss Cross','Jazz','Vinyl',NULL,NULL),
	(875,'Dixie Chicks','Taking The Long Way','Country','CD',NULL,NULL),
	(876,'Aretha Franklin','Greatest Hits (1980-1994)','R&B','CD',NULL,NULL),
	(877,'Poco','Ultimate Collection','Rock','CD',NULL,NULL),
	(878,'Billy Lee Riley','Red Hot','RockaBilly','Download',NULL,NULL),
	(879,'Roberta Flack','Killing Me Softly','R&B','Download',NULL,NULL),
	(880,'ADELE','Rumour Has It - Single','Pop','Download',NULL,NULL),
	(881,'Queen','Classic Queen','Rock','Download',NULL,NULL),
	(882,'Queen','Queen_ Greatest Hits','Rock','Download',NULL,NULL),
	(883,'Queen','Live At Wembley Stadium [Disc 1]','Rock','download',NULL,NULL),
	(884,'Queen','Live At Wembley Stadium [Disc 2]','Rock','download',NULL,NULL),
	(885,'Bill Monroe','Live 1964','Country','CD',NULL,NULL),
	(886,'Blues Image','Rhino Hi-Five_ Blues Image - EP','Rock','Download',NULL,NULL),
	(887,'Nine Black Alps','Everything Is','Rock','Download',NULL,NULL),
	(888,'Emmylou Harris','Red Dirt Girl','Country','CD',NULL,NULL),
	(889,'Emmylou Harris','Light of the Stable','Country','CD',NULL,NULL),
	(890,'Emmylou Harris','Elite Hotel','Country','Vinyl',NULL,NULL),
	(891,'Emmylou Harris','All I Intended To Be','Country','CD',NULL,NULL),
	(892,'Emmylou Harris','Wrecking Ball','Country','CD',NULL,NULL),
	(893,'Emmylou Harris','Heartaches & Highways_ The Very Best of Emmylou Harris','Country','CD',NULL,NULL),
	(894,'Emmylou Harris','Hard Bargain','Country','CD',NULL,NULL),
	(895,'Citizen Cope','Every Waking Moment','Rock','CD',NULL,NULL),
	(896,'Reflejo de Luna','The Tango Club Night, Vol. 2','Pop','Download',NULL,NULL),
	(897,'Dave Brubeck Quartet','Take Five','Jazz','Vinyl',NULL,NULL),
	(898,'Dave Brubeck Quartet','Back Home','Jazz','Vinyl',NULL,NULL),
	(899,'The Kinks','Lola Versus Powerman And The Moneygoround, Part One','Rock','Download',NULL,NULL),
	(900,'The Kinks','Pirate Radio (Motion Picture Soundtrack) [Deluxe Version]','Rock','Download',NULL,NULL),
	(901,'The Kinks','Kinks-Size','Rock','Download',NULL,NULL),
	(902,'The Kinks','Kinks','Rock','Vinyl',NULL,NULL),
	(903,'The B-52''s','Wild Planet','Rock','CD',NULL,NULL),
	(904,'Infamous Stringdusters','Fork in the Road','BlueGrass','Download',NULL,NULL),
	(905,'The Turtles','Save The Turtles_  The Turtles Greatest Hits','Rock','Download',NULL,NULL),
	(906,'Bob Marley','Legend (Remastered)','Regae','Download',NULL,NULL),
	(907,'Del Shannon','Little Town Flirt','Pop','Download',NULL,NULL),
	(908,'Stanley Turrentine','Blue Note Stanley Turrentine Quintet_Sextet Studio Sessions','Jazz','Download',NULL,NULL),
	(909,'Dick Dale & His Del-Tones','Surfers'' Choice','Rock','Download',NULL,NULL),
	(910,'Brecker Brothers','Back To Back','Jazz','Vinyl',NULL,NULL),
	(911,'Brecker Brothers','The Brecker Brothers','Jazz','Vinyl',NULL,NULL),
	(912,'Brecker Brothers','Dont Stop The Music','Jazz','Vinyl',NULL,NULL),
	(913,'ZZ_ZTest','Test_Album2','TestGenre','TestType',NULL,NULL),
	(914,'ZZ_ZTest','Test_Album1','TestGenre','TestType',NULL,NULL),
	(915,'Yo-Yo Ma','Songs of Joy & Peace','Pop','Download',NULL,NULL),
	(916,'Mason Williams','Music - 1968-1971','Rock','Download',NULL,NULL),
	(917,'The Diamonds','The Best of the Diamonds_ The Mercury Years','Rock','Download',NULL,NULL),
	(918,'Death Cab for Cutie','Underneath the Sycamore - Single','Pop','Download',NULL,NULL),
	(919,'Ottmar Liebert','Surrender 2 Love_ The Best of Ottmar Liebert, Vol. 2','Pop','CD',NULL,NULL),
	(920,'Ottmar Liebert','Leaning into the Night','Pop','CD',NULL,NULL),
	(921,'Ottmar Liebert','Solo Para Ti','Pop','CD',NULL,NULL),
	(922,'Sir Douglas Quintet','The Best Of Sir Douglas Quintet','TexMex','CD',NULL,NULL),
	(923,'Sir Douglas Quintet','The Great Sir Douglas Quintet Live','TexMex','Download',NULL,NULL),
	(924,'Sir Douglas Quintet','Mendocino','TexMex','download',NULL,NULL),
	(925,'Peter, Paul & Mary','The Very Best of Peter, Paul and Mary','Folk','Download',NULL,NULL),
	(928,'Bob Dylan','Time They Are A-Changin','Folk','Vinyl',NULL,NULL),
	(929,'Bob Dylan','Slow Train Coming [Remastered]','Folk','CD',NULL,NULL),
	(930,'Bob Dylan','Planet Waves','Folk','Vinyl',NULL,NULL),
	(931,'Bob Dylan','Time Out Of Mind','Folk','CD',NULL,NULL),
	(932,'Bob Dylan','World Gone Wrong','Folk','CD',NULL,NULL),
	(933,'Bob Dylan','Love And Theft','Folk','CD',NULL,NULL),
	(934,'Bob Dylan','Nashville Skyline','Folk','Vinyl',NULL,NULL),
	(935,'Bob Dylan','Modern Times','Folk','Download',NULL,NULL),
	(936,'Bob Dylan','Bob Dylan','Folk','Vinyl',NULL,NULL),
	(937,'Billie Holiday','The Billie Holiday Story Volume II','Blues','Vinyl',NULL,NULL),
	(938,'Vienna Teng','Waking Hour','Pop','CD',NULL,NULL),
	(939,'Mark Lanegan','Imitations','Folk','CD',NULL,NULL),
	(940,'Grand Funk Railroad','Closer To Home [2002 Reissue]','Rock','CD',NULL,NULL),
	(941,'Ian Anderson','Thick As A Brick 2','Rock','CD',NULL,NULL),
	(942,'Jeff Beck','You Had It Coming','Rock','CD',NULL,NULL),
	(943,'Neil Diamond','All-Time Greatest Hits','Pop','CD',NULL,NULL),
	(944,'Gladys Knight & The Pips','','R&B','CD','',NULL),
	(945,'Elton John & Leon Russell','The Union','Pop','CD',NULL,NULL),
	(946,'Donovan','A Gift From A Flower To A Garden','Folk','Vinyl',NULL,NULL),
	(947,'The Doobie Brothers','Farewell Tour (Live) [Remastered]','Rock','Download',NULL,NULL),
	(948,'Yes','Going For The One [Bonus Tracks]','Rock','CD','Yes_Going_for_the_One.jpg',521),
	(949,'Neil Young & Crazy Horse','Live Rust','Rock','CD','Neil_Young_&_Crazy_Horse-Live_Rust.jpg',522),
	(950,'Neil Young & Crazy Horse','Psychedelic Pill [Disc 2]','Rock','CD','NeilYoung_Psychedelicpill.jpg',523),
	(951,'Neil Young & Crazy Horse','Psychedelic Pill [Disc 1]','Rock','CD','NeilYoung_Psychedelicpill.jpg',522),
	(952,'The Marshall Tucker Band','Where We All Belong','Rock','CD','MarshalTucker_whereWeAllBelong.jpg',595),
	(953,'The Marshall Tucker Band','A New Life','Rock','CD',NULL,NULL),
	(954,'The Who','The Who Sell Out','Rock','CD','The_who_sell_out.jpg',524),
	(955,'The Who','Live At Leeds','Rock','CD',NULL,NULL),
	(956,'Yo La Tengo','Stuff Like That There','Rock','CD',NULL,NULL),
	(957,'Sting','The Last Ship','Pop','CD',NULL,NULL),
	(958,'Jeff Beck','Live+','Rock','CD','JeffBeck_Live+.jpeg',527),
	(959,'Queenryche','Take Cover','Rock','CD','Queenryche_Takecover.jpg',525),
	(960,'The Turtles','Save The Turtles_ The Turtles Greatest Hits','Rock','CD',NULL,NULL),
	(961,'Wilson Pickett','The Exciting Wilson Pickett','R&B','CD','WilsonPicket_The_Exciting.jpeg',526),
	(962,'Booker T. & The Mg''s','Green Onions','R&B','CD','BookerT.&theMG''sGreenOnions.jpg',528),
	(963,'Eric Clapton','Behind The Sun','Rock','CD',NULL,NULL),
	(964,'Andy Narell','Stickman','Jazz','Vinyl','AndyNarell_Stickman.jpeg',529),
	(965,'The Doors','Morrison Hotel','Rock','CD',NULL,NULL),
	(966,'Crosby, Stills, Nash & Young','Deja Vu','Rock','CD',NULL,NULL),
	(967,'David Bowie','Earthling','Rock','CD','Bowie_Earthling.jpg',531),
	(968,'Bob Seger','Ride Out [Deluxe]','Rock','CD',NULL,NULL),
	(969,'Blondie','Eat To The Beat','Rock','CD','Blondie_EatTheBeat.jpg',532),
	(970,'Eric Clapton','Backless','Rock','CD',NULL,NULL),
	(971,'Eric Clapton','I Still Do','Rock','CD','Clapton_I_Still_Do.jpg',530),
	(972,'Ringo Starr','Postcards From Paradise','Rock','CD',NULL,NULL),
	(973,'Lester Young','Pres','Jazz','Vinyl','LesterYoung_Pres.jpeg',541),
	(974,'Tom Petty & The Heartbreakers','Greatest Hits','Rock','CD',NULL,NULL),
	(975,'Compilations','Crossroads Guitar Festival 2013 [Live] [Disc 1]','Rock','CD','EricClapton_Crossroads.jpg',539),
	(976,'Compilations','Crossroads Guitar Festival 2013 [Live] [Disc 2]','Rock','CD','EricClapton_Crossroads.jpg',540),
	(977,'Elton John','The Big Picture','Pop','CD',NULL,NULL),
	(978,'Journey','Greatest Hits','Rock','CD',NULL,NULL),
	(979,'Pink Floyd','Pulse [Disc 1]','Rock','CD','PinkFloyd_Pulse.jpg',535),
	(980,'Pink Floyd','Pulse [Disc 2]','Rock','CD','PinkFloyd_Pulse.jpg',536),
	(981,'Jerry Garcia Band','GarciaLive, Vol. 5 [Disc 1]','Rock','CD','JerryGarciaBand_Vol_5.jpg',537),
	(982,'Jerry Garcia Band','GarciaLive, Vol. 5 [Disc 2]','Rock','CD','JerryGarciaBand_Vol_5.jpg',538),
	(983,'Jerry Garcia Band','GarciaLive, Vol. 8 [Disc 2]','Rock','CD','Garcia-Live-Volume-8.jpg',534),
	(984,'Jerry Garcia Band','GarciaLive, Vol. 8 [Disc 1]','Rock','CD','Garcia-Live-Volume-8.jpg',533),
	(985,'Thin Lizzy','Jailbreak','Rock','CD',NULL,NULL),
	(986,'Thin Lizzy','Jailbreak [Disc 2]','Rock','CD',NULL,NULL),
	(987,'Thin Lizzy','Bad Reputation','Rock','CD',NULL,NULL),
	(988,'Leonard Cohen','Popular Problems','Pop','CD',NULL,NULL),
	(989,'Neil Young','A Letter Home','Rock','CD',NULL,NULL),
	(990,'Triumph','Greatest Hits Remixed','Rock','CD',NULL,NULL),
	(991,'The Charlie Daniels Band','The Ultimate Charlie Daniels Band [Disc 1]','Country','CD',NULL,NULL),
	(992,'The Charlie Daniels Band','The Ultimate Charlie Daniels Band [Disc 2]','Country','CD',NULL,NULL),
	(993,'Paul McCartney','Kisses On The Bottom','Pop','CD',NULL,NULL),
	(994,'Traffic','John Barleycorn Must Die','Rock','CD',NULL,NULL),
	(995,'Neil Young & Crazy Horse','Everybody Knows This Is Nowhere','Rock','CD',NULL,NULL),
	(996,'Marty Robbins','Gunfighter Ballads And Trail Songs','Country','CD',NULL,NULL),
	(997,'Chris Robinson Brotherhood','Any Way You Love, We Know How You Feel','Rock','CD',NULL,NULL),
	(998,'Chris Robinson Brotherhood','If You Lived Here, You Would Be Home By Now [EP]','Rock','CD',NULL,NULL),
	(999,'Jimi Hendrix','Blue Wild Angel_ Jimi Hendrix Live At The Isle Of Wight','Rock','CD','JimiHendrix_BlueWildAngel.jpg',542),
	(1000,'Leonard Cohen','Songs From The Road','Pop','CD',NULL,NULL),
	(1001,'Leonard Cohen','Dear Heather','Pop','CD',NULL,NULL),
	(1002,'Leonard Cohen','Can''t Forget_ A Souvenir of the Grand Tour','Pop','CD','LenardCohen_cantforget.jpg',543),
	(1003,'Leonard Cohen','Ten New Songs','Pop','CD',NULL,NULL),
	(1004,'Leonard Cohen','Old Ideas','Pop','CD',NULL,NULL),
	(1005,'Leonard Cohen','You Want It Darker','Pop','CD',NULL,NULL),
	(1006,'Grateful Dead','Go To Heaven','Rock','CD',NULL,NULL),
	(1007,'The Beatles','Revolver','Rock','CD',NULL,NULL),
	(1008,'Blue Oyster Cult','The Essential Blue Oyster Cult','Rock','CD','BlueOysterCult_The_Essential.jpg',544),
	(1009,'Foghat','The Best Of Foghat','Rock','CD','Foghat_The_BestOf.jpg',546),
	(1010,'Beck','Morning Phase','Rock','CD','Beck_Morning_Phase.jpg',545),
	(1011,'Boston','Boston','Rock','CD',NULL,NULL),
	(1012,'Grateful Dead','Blues For Allah','Rock','CD',NULL,NULL),
	(1013,'Jeff Beck','Blow By Blow','Rock','CD',NULL,NULL),
	(1014,'Humble Pie','Smokin''','Rock','CD',NULL,NULL),
	(1015,'Moody Blues','On The Threshold Of A Dream','Rock','CD',NULL,NULL),
	(1016,'Iron & Wine','Archive Series, Vol. No. 1','Rock','CD','Iron&wine_ArchiveSeriesVolume1.jpg',549),
	(1017,'Iron & Wine','Kiss Each Other Clean','Rock','CD','Iron&wine_Kiss_Each_Other_Clean.jpg',548),
	(1018,'Motley Crue','Shout At The Devil [Bonus Tracks]','Rock','CD',NULL,NULL),
	(1019,'Huey Lewis & The News','Huey Lewis & The News Greatest Hits','Rock','CD',NULL,NULL),
	(1020,'BJ Thomas','B.J. Thomas_ Greatest Hits','Rock','CD','B.J. Thomas_ Greatest Hits',551),
	(1021,'T. Rex','The Slider','Rock','CD','T_Rex_The_Slider.jpg',552),
	(1022,'Dexter Gordon','Homecoming_ Live At The Village Vanguard [Live] [Disc 1]','Jazz','CD','DexterGordon_Homecoming.jpeg',550),
	(1023,'Dexter Gordon','Homecoming_ Live At The Village Vanguard [Live] [Disc 2]','Jazz','CD','DexterGordon_Homecoming.jpeg',550),
	(1024,'Cheap Trick','Bang, Zoom, Crazy... Hello','Rock','CD',NULL,NULL),
	(1025,'Cheap Trick','We''re All Alright!','Rock','CD',NULL,NULL),
	(1026,'Emerson, Lake & Palmer','Emerson, Lake & Palmer','Rock','CD','EmersonlakePalmer_cover.jpg',554),
	(1027,'AC_DC','Rock Or Bust','Rock','CD',NULL,NULL),
	(1028,'Jewel','Sweet And Wild','Country','CD',NULL,NULL),
	(1029,'Santana','Santana IV','TexMex','CD',' Santana_IV.jpg',552),
	(1030,'Dave Mason','Dave Mason The Definitive Collection','Rock','CD','DaveMason_DefintiveCollection.jpeg',558),
	(1031,'The Hollies','On a Carousel','Rock','CD','Hollies_On_A_Caraousel.jpg',555),
	(1032,'Talking Heads','The Best Of Talking Heads','Rock','CD',NULL,NULL),
	(1033,'Fleetwood Mac','Fleetwood Mac''s Greatest Hits','Rock','CD','Fleetwood_Mac_Greatest_Hits_1971.jpg',556),
	(1034,'Eric Clapton','461 Ocean Boulevard','Rock','CD',NULL,NULL),
	(1035,'R.E.M.','Murmur','Rock','CD',NULL,NULL),
	(1036,'R.E.M.','Murmur','Rock','CD',NULL,NULL),
	(1037,'R.E.M.','Accelerate','Rock','CD','REM_Accerlerate.jpeg',557),
	(1038,'Isaac Hayes','Isaac Hayes Greatest Hit Singles','R&B','CD','IsaacHayes_greatest_singles.jpg',559),
	(1039,'Pink Floyd','A Saucerful Of Secrets','Rock','CD','PinkFloyd_SaucersOfScrets.jpg',560),
	(1040,'John Mellencamp','Nothing Like I Planned Greatst Hits Vol. 3','Rock','CD','JohnMellencamp_NothingLikeIPlanned.jpg',561),
	(1041,'Pearl Jam','Yield','Rock','CD',NULL,NULL),
	(1042,'Led Zeppelin','Physical Graffiti [Disc 1]','Rock','CD',NULL,NULL),
	(1043,'Led Zeppelin','Physical Graffiti [Disc 1]','Rock','CD',NULL,NULL),
	(1044,'Devo','Freedom Of Choice [Deluxe Remastered Edition]','Rock','CD','Devo_FreedomOfChoice.jpg',562),
	(1045,'Paul McCartney','Ram','Pop','CD','McCartney_Ram.jpg',563),
	(1046,'Paul McCartney','Ram [Disc 2]','Pop','CD','McCartney_Ram.jpg',563),
	(1047,'John Lennon','Mind Games','Rock','CD',NULL,NULL),
	(1048,'Lenny Kravitz','LENNY KRAVITZ GREATEST HITS','Rock','CD',NULL,NULL),
	(1049,'Grateful Dead','Wake Of The Flood [Expanded]','Rock','CD',NULL,NULL),
	(1050,'Leonard Cohen','Songs From A Room','Rock','CD','LenardCohen_Songs_from_a_room.jpg',564),
	(1051,'Tom Jones','Spirit In The Room','Pop','CD',NULL,NULL),
	(1052,'Jewel','Picking Up The Pieces','Country','CD',NULL,NULL),
	(1053,'The Grass Roots','The Complete Original Dunhill_ABC Hit Singles','Rock','CD','GrassRoots_CompleteOriginal.jpg',567),
	(1054,'Linkin Park','Recharged','Rock','CD',NULL,NULL),
	(1055,'R.E.M.','Automatic For The People','Rock','CD','REM_AutomaticForPeople.jpg',565),
	(1056,'The Sonics','Here Are The Sonics!!!','Rock','CD',NULL,NULL),
	(1057,'Keith Richards','Crosseyed Heart','Rock','CD',NULL,NULL),
	(1058,'Van Morrison','Astral Weeks','Rock','CD','VanMorrison_AstralWeeks.jpg',566),
	(1059,'The Spencer Davis Group','Keep On Running','Rock','Download',NULL,NULL),
	(1060,'The Guess Who','Live At The Paramount','Rock','CD',NULL,NULL),
	(1061,'Dave Matthews Band','Live At Red Rocks 8.15.95 [Disc 1]','Rock','CD',NULL,NULL),
	(1062,'Dave Matthews Band','Live At Red Rocks 8.15.95 [Disc 2]','Rock','CD',NULL,NULL),
	(1063,'ZZ Top','Live Greatest Hits From Around The World','Rock','CD',NULL,NULL),
	(1064,'Lynyrd Skynyrd','Street Survivors','Rock','CD',NULL,NULL),
	(1065,'Elton John','Goodbye Yellow Brick Road','Rock','CD','EltonJohn_YellowBrickRoad.jpg',569),
	(1066,'Heart','Heart','Rock','CD','Heart_Heart.jpg',568),
	(1067,'Elvis Costello','My Aim Is True','Rock','CD',NULL,NULL),
	(1068,'Chicago','Chicago VIII [Bonus Tracks]','Rock','CD','chicago_VIII.jpg',570),
	(1069,'The Beatles','The Beatles/Let It Be... Naked [Disc 2]','Rock','CD',NULL,NULL),
	(1070,'The Beatles','The Beatles/Let It Be... Naked [Disc 1]','Rock','CD',NULL,NULL),
	(1071,'Joshua Redman','Walking Shadows','Jazz','CD',NULL,NULL),
	(1072,'The Cal Tjader Quintet','Monterey Concerts','Jazz','CD',NULL,NULL),
	(1073,'B.B. King','Live In Cook County Jail','Blues','CD','BBKing_CookCountyJail.jpg',573),
	(1074,'B.B. King','Live At The Regal','Blues','CD','BBKing_LiveAtRegal.jpg',574),
	(1075,'John Coltrane','Ballads (Deluxe Edition) [Disc 1]','Jazz','CD','JohnColtrane_Ballads.jpg',571),
	(1076,'John Coltrane','Ballads (Deluxe Edition) [Disc 2]','Jazz','CD','JohnColtrane_Ballads.jpg',571),
	(1077,'Pink Floyd','The Final Cut','Rock','CD',NULL,NULL),
	(1078,'Crooked Still','Some Strange Country','Folk','CD','CrookedStill_Strange_Country.jpg',571),
	(1079,'Faces','Ooh La La','Rock','Download',NULL,NULL),
	(1080,'Jethro Tull','The Best Of Jethro Tull_ The Anniversary Collection [Disc 2]','Rock','CD','JethroTull_Anniverary.jpg',578),
	(1081,'Jethro Tull','The Best Of Jethro Tull_ The Anniversary Collection [Disc 1]','Rock','CD','JethroTull_Anniverary.jpg',577),
	(1082,'Talking Heads','Little Creatures','Rock','CD','TalkingHeads_LittleCreatures.jpg',584),
	(1083,'Talking Heads','Talking Heads_ 77','Rock','CD','TalkingHeads_77.jpg',585),
	(1084,'Lynyrd Skynyrd','Pronounced Leh-nerd Skin-nerd','Rock','CD','Lynyrdskynyrd_Pronounced.jpg',583),
	(1085,'The Sonics','Boom','Rock','CD','Sonics_Boom.jpg',582),
	(1086,'Rod Stewart','The Definitive Rod Stewart','Downlaod','CD',NULL,NULL),
	(1087,'Rod Stewart','Another Country','Rock','CD','RodStewart_AnotherCountry.jpg',581),
	(1088,'John Coltrane','Stardust','Jazz','CD','JohnColtrane_StarDust.jpg',580),
	(1089,'Marsalis-Branford','Upward Spiral','Jazz','CD','Marsalis_UpwardSpiral.jpg',579),
	(1090,'Rod Stewart','Gold [Disc 1]','Rock','CD','RodStewarts_Gold.jpg',576),
	(1091,'Rod Stewart','Gold [Disc 2]','Rock','CD','RodStewarts_Gold.jpg',575),
	(1092,'Mark Knopfler','Tracker','Rock','CD',NULL,NULL),
	(1093,'Mark Knopfler','Get Lucky','Rock','CD',NULL,NULL),
	(1094,'Black Sabbath','Paranoid','Rock','CD',NULL,NULL),
	(1095,'Eric Clapton & Steve Winwood','Live From Madison Square Garden [Disc 1]','Rock','CD',NULL,NULL),
	(1096,'Eric Clapton & Steve Winwood','Live From Madison Square Garden [Disc 2]','Rock','CD',NULL,NULL),
	(1097,'Spanky & Our Gang','The Best Of Spanky & Our Gang 20th Century Masters The Millennium Collection','Rock','CD','SpankAndOurGang_TheBestOf.jpg',586),
	(1098,'Alison Krauss','Windy City','Country','CD','Krauss_WindyCity.jpg',587),
	(1101,'The Marshall Tucker Band','Carolina Dreams','Rock','CD','MarshalTucker_CarolinaDreams.jpg',588),
	(1102,'The Zombies','Odessey & Oracle [Bonus Tracks]','Rock','CD','Zombies_OdesseyOracle.jpg',589),
	(1103,'Paul Simon','Graceland: The Remixes','Pop','CD','PaulSimon_Graceland.jpg',590),
	(1104,'T. Rex','Electric Warrior','Rock','CD',NULL,NULL),
	(1105,'Traveling Wilburys','Traveling Wilburys Collection [Disc 1]','Rock','CD','TravelingWilburys_BonusTracks.jpg',591),
	(1107,'Traveling Wilburys','Traveling Wilburys Collection [Disc 3]','Rock','CD','TravelingWilburys_BonusTracks.jpg',592),
	(1108,'Tom Waits','Bad As Me','Rock','CD','TomWaits_BasAsMe.jpg',593),
	(1109,'Tower of Power','Great American Soulbook','R&B','CD','TowerOfPower_GreatAmericanSoulBook.jpg',594);
