INSERT INTO album_covers (cover_idx, album_cover, album, description)
VALUES
	(1,'2001_A_Space_Odyssey_(soundtrack).jpg','Space Odessy Sound Track','No description'),
	(2,'Ace Frehley.jpg','Ace Frehley','No description'),
	(3,'Aerosmith_Sweet_Emotions.jpg','Not Used','No description'),
	(4,'5thDimesion_The_Essential.jpg','The Essential Fifth Dimension','No description'),
	(5,'Alabama.jpg','Alabama Greatest Hits','No description'),
	(6,'Alabama_SouthernDrawl.jpg','Southern Drawl','No description'),
	(7,'AlexHargleaves_Prelude.jpg','Prelude','No description'),
	(8,'AlisonKrause_Paperairplaneakus.jpg','Paper Airplane','No description'),
	(9,'Alison_Krauss-Forget_About_It.jpg','Forget About It','No description'),
	(10,'Allman Bros At Fillmore.jpg','Forget About It','No description'),
	(11,'AllmanBothers_Eat A Peach.jpg','Eat A Peach','No description'),
	(12,'AllmanBrothers_Beginnings.jpg','Beginnings','No description'),
	(13,'AllmanBrothers_Brothers And Sisters.jpg','Brothers And Sisters','No description'),
	(14,'Alvin Lee_In Flight.jpg','In Flight','No description'),
	(15,'AlvinLee_On_Road_To_Freedom.jpg','On The Road To Freedom Alvin Lee & Mylon LeFevre','No description'),
	(16,'AlvinLee_Rocket_Fuel.jpeg','Rocket Fuel','No description'),
	(17,'AnimalOriginalHits.jpg','The Animals Original Hits','No description'),
	(18,'Aretha Franklin.jpg','Greatest Hits (1980-1994)','No description'),
	(19,'ArloGutherie_Alices_Restruant.jpg','Alices Restaurant','No description'),
	(20,'ArloGuthrieRunningDownTheroad.jpg','Running Down The Road','No description'),
	(21,'Arlo_Pete_Seger.jpg','Pete Seeger & Arlo Guthrie - Together In Concert','No description'),
	(22,'ArtOfMcCartney.jpg','The Art Of McCartney [Disc 1]','No description'),
	(23,'ArtOfMcCartney.jpg','The Art Of McCartney [Disc 2]','No description'),
	(24,'Bachman-Turner_Overdrive_-_Not_Fragile.jpg','Not Fragile','No description'),
	(25,'Badfinger.jpg','Not Used','No description'),
	(26,'BadFinger_TheVeryBestOf.jpg','The Very Best Of Badfinger','No description'),
	(27,'BarryMcGuire_EveOfDestruction.jpg','Eve Of Destruction','No description'),
	(28,'Beach Boys 20 Greatest.jpg','The Beach Boys 15 Big Ones','No description'),
	(29,'BeachBoys_15BigOnesCover.jpg','The Beach Boys 15 Big Ones','No description'),
	(30,'Beach Boys 20 Greatest.jpg','The Beach Boys 20 Golden Greats','No description'),
	(31,'Beatles 62-66.jpg','Beatles 62-66','No description'),
	(32,'Beatles Hard Days Nigh.jpg','Hard Days Night','No description'),
	(33,'Beatles Help.jpeg','Help','No description'),
	(34,'Beatles Meet.jpg','Meet The Beatles','No description'),
	(35,'Beatles Rubber Soul.jpg','Rubber Soul','No description'),
	(36,'Beatles Rubber Soul.jpg','Rubber Soul (North American)','No description'),
	(37,'Beatles Something New.jpg','Something New','No description'),
	(38,'Beatles songs pics stories.jpg','The Beatles Songs Pictures And Stories','No description'),
	(39,'Beatles VJ.jpg','Beatles IV','No description'),
	(40,'beatles white album.jpg','White Album','No description'),
	(41,'Beatles-MagicalMysteryTourDoubleEPcover.jpg','Magical Mystery Tour','No description'),
	(42,'Beatles65.jpg','Beatles 65','No description'),
	(43,'Beatlesforsale.jpg','Beatles For Sale','No description'),
	(44,'BeatlesSecondAlbumreissuecover.jpg','The Beatles Second Album','No description'),
	(45,'Beatles_TheBeatlesSomethingNewreissuecover.jpg','Something New','No description'),
	(46,'Beatles_YesterdayandTodayalbumcover.jpg','Yesterday and Today','No description'),
	(47,'Beatles_abbey road.jpg','Abbey Road','No description'),
	(48,'Beatles_beatles white album.jpg','White Album','No description'),
	(49,'Beatles_sgt pepper.jpg','Sgt Peppers Lonely Hearts Club Band','No description'),
	(50,'Beatlesforsale.jpg','Beatles For Sale','No description'),
	(51,'BeeGees_MrNatural.jpeg','Mr. Natural','No description'),
	(52,'BeeGees_main_coarse.jpeg','Main Course','No description'),
	(53,'BernsteinConductsWagner.jpeg','Bernstein Conducts Wagner','No description'),
	(54,'Best of BeeGees.jpg','Best Of The BeeGees','No description'),
	(55,'Best_of_Bread.jpeg','The Best Of Bread','No description'),
	(56,'BillMonroe1964.jpeg','Live 1964','No description'),
	(57,'BillWithers Hits.jpg','Bill Withers Greatest Hits','No description'),
	(58,'BillyJoel_52nd Street.jpg','52nd Street','No description'),
	(59,'BlackSabbath-Technical-Ecstasy.jpg','Technical Ecstasy','No description'),
	(60,'BlackSabbath_SbS.jpg','Sabbath Bloody Sabbath','No description'),
	(61,'BlindFaith.jpg','Blind Faith','No description'),
	(62,'BlindFaithBlindFaith.jpg','Blind Faith','No description'),
	(63,'BloodSweatTears_3.jpg','Blood Sweat & Tears 3','No description'),
	(64,'BloodSweatTears_New Blood.jpg','New Blood','No description'),
	(65,'BloodSweatTears_No Sweat.jpg','No Sweat','No description'),
	(66,'BlueOysterCult_Imaginos.jpg','Imaginos','No description'),
	(67,'BlueOysterCult_Imaginos_BlueOstercult.jpg','Imaginos','No description'),
	(68,'BobDylan Bob Dylan.jpg','Bob Dylan','No description'),
	(69,'BobDylan_Love_and_Theft.jpg','Love And Theft','No description'),
	(70,'BobDylan_Nashville Skyline.jpg','Nashville Skyline','No description'),
	(71,'BobDylan_Planet Waves.jpg','Planet Waves','No description'),
	(72,'BobDylan_Slow_Train_coming.jpg','Slow Train Coming [Remastered]','No description'),
	(73,'BobDylan_The Times Are A Changin.jpg','Time They Are A-Changin','No description'),
	(74,'BobDylan_Time are changin.jpg','Time They Are A-Changin','No description'),
	(75,'BobDylan_Time_out_of_mind.jpg','Time Out Of Mind','No description'),
	(76,'BobDylan_World_Gone_Wrong.jpg','World Gone Wrong','No description'),
	(77,'BobSeger Greatest Hits.jpg','Bob Seger Greatest Hits','No description'),
	(78,'BobbyDarin.jpeg','Mack the Knife','No description'),
	(79,'BobbyDarin_MackTheKnife.jpeg','Mack the Knife','No description'),
	(80,'Bolero.jpeg','Ravel_ Bolero','No description'),
	(81,'Bon_Jovi_Album.jpg','Bon Jovi','No description'),
	(82,'Bonston Pops Blue Danube.jpg','The Blue Danube','No description'),
	(83,'Boston-Life-Love-Hope.jpg','Life, Love & Hope','No description'),
	(84,'Boston_LifeLove&Hope.jpg','Life, Love & Hope','No description'),
	(85,'Bowie.jpg','Hunky Dory','No description'),
	(86,'Bozz Scaggs Silk Degrees.jpg','Silk Degrees','No description'),
	(87,'Bozz Scaggs Silk Degrees.jpg','Bozz Scaggs Hits','No description'),
	(88,'BozzScaggsHits.jpg','Bozz Scaggs Hits','No description'),
	(89,'BranfordMarsailes_romances4sax.jpg','Romances For Saxophone','No description'),
	(90,'Bread_The_Best_of_Bread.jpg','The Best Of Bread','No description'),
	(91,'Brecker Bros Back To Back.jpg','Back To Back','No description'),
	(92,'BreckerBrothers.jpg','The Brecker Brothers','No description'),
	(93,'BreckerBrothers_Dont Stop The Music.jpeg','Dont Stop The Music','No description'),
	(94,'Brecker_City Scape.jpg','CityScape','No description'),
	(95,'Brenda Lee.jpeg','The Definitive Collection Brenda Lee','No description'),
	(96,'Brubeck_Take Five.jpg','Take Five','No description'),
	(97,'Brubeck_back home.jpg','Back Home','No description'),
	(98,'Brubeck_new wine.jpg','New Wine','No description'),
	(99,'BruceSpringsteen_Born_to_Run_(Front_Cover).jpg','Born To Run','No description'),
	(100,'BruceSpringsteen_High Hopes.jpg','High Hopes','No description'),
	(101,'Bruce_Springsteen-Magic.jpg','Magic','No description'),
	(102,'Bruce_Springsteen_-_Magic.jpg','Magic','No description'),
	(103,'Bruce_Springsteen_-_Nebraska.jpg','Nebraska','No description'),
	(104,'Bruce_Springsteen_BornInUSA.jpg','Born In The USA','No description'),
	(105,'Buffalo Springfield.jpg','Retrospective_ The Best of Buffalo Springfield','No description'),
	(106,'Buffet_changes in lattitude.jpg','Changes In Latitudes-Havana Day Dreamin','No description'),
	(107,'Buffet_sonOfaSailure.jpg','Son Of A Sailor','No description'),
	(108,'Buffett_LivingAndDying.jpeg','Livign And Dying In Three Quarter Time','No description'),
	(109,'Butterfield Blues Band Live.jpeg','The Paul Butterfield Blues Band','No description'),
	(110,'PaulButterfield_East-West.jpg','East-West','No description'),
	(111,'CaroleKingTapestry.jpg','Tapestry','No description'),
	(112,'Celtic-Christmas.jpg','Celtic Christmas','No description'),
	(113,'ChaplinsBack.jpeg','Chaplins back','No description'),
	(114,'Charlie Daniels A Decade.jpg','Charlie Daniels Band A Decade Of Hits','No description'),
	(115,'Charlie Rich.bmp','Every Time You Touch Me','No description'),
	(116,'CharlieDaniels_Nightrider.jpg','Nightrider','No description'),
	(117,'CharlieRich_Best Of Charlie Rich.bmp','Best of Charlie Rich','No description'),
	(118,'Cheap_Trick_In_Color.jpg','In Color [Bonus Tracks]','No description'),
	(119,'Chicago.jpg','Chicago','No description'),
	(120,'ChicagoLiveInJapan.jpg','Chicago Live In Japan [Disc 1]','No description'),
	(121,'ChicagoLiveInJapan.jpg','Chicago Live In Japan [Disc 2]','No description'),
	(122,'Chicago_-_Chicago_V.jpg','Chicago V','No description'),
	(123,'Chicago_LiveInJapan.jpg','Chicago Live In Japan Disc 2','No description'),
	(124,'Chicago_The_Very_Best_of_Chicago_Only_the_Beginning.jpg','The Very Best of Chicago_ Only the Beginning [Disc 1]','No description'),
	(125,'Chicago_The_Very_Best_of_Chicago_Only_the_Beginning.jpg','The Very Best of Chicago_ Only The Beginning [Disc 2]','No description'),
	(126,'Chick_Corea_Expressions.jpg','Expressions','No description'),
	(127,'Claptonridingwiththeking.jpg','Riding With The King','No description'),
	(128,'ClarenceGatemouthBrown.jpg','Blackjack','No description'),
	(129,'Coasters_The Very Best Of The Coasters.jpg','The Very Best Of The Coasters','No description'),
	(130,'Coasters_TheVeryBest_Of.jpg','The Very Best Of The Coasters','No description'),
	(131,'Coltrane Giant Steps.jpg','Giant Steps','No description'),
	(132,'ColtraneAtThe_Village.jpg','Coltrane Live At the Village Vangard Again!','No description'),
	(133,'Coltrane_Favorite_Things.jpg','My Favorite Things','No description'),
	(134,'Coltrane_Hartman.jpg','John Coltrane & Johnny Hartman','No description'),
	(135,'CreamCream.jpg','Cream','No description'),
	(136,'CreamOfClapton.jpg','The Cream Of Clapton','No description'),
	(137,'Cream_The_Very_Best_of_Cream_(album)_cover_art.jpg','Fresh Cream','No description'),
	(138,'Cream_fresh_cream.jpg','Fresh Cream','No description'),
	(139,'CrookedStill_Shaken By A Low Sound.jpg','Shaken By A Low Sound','No description'),
	(140,'CrosbyStillNashYoung.jpg','Crosby, Stills & Nash','No description'),
	(141,'Crosbystillsandnash.jpg','Crosby, Stills & Nash','No description'),
	(142,'DaveBruebeck_NewWine.jpg','New Wine','No description'),
	(143,'DaveMason_spilt-cocnut.jpg','Split Coconut','No description'),
	(144,'DaveMatthewsBandEveryday.jpg','Everyday','No description'),
	(145,'DavidAllenCoe.jpg','The Essential David Allan Coe','No description'),
	(146,'David_Bowie-Heroes.png','_Heroes_','No description'),
	(147,'David_Bowie_Hunky_Dory.jpg','Hunky Dory','No description'),
	(148,'DavisBowieAladdinSane.jpg','Aladdin Sane','No description'),
	(149,'DeepPurpleLiveInCopenhagen1972.jpg','Live In Copenhagen 1972 [Disc 2]','No description'),
	(150,'DeepPurpleLiveInCopenhagen1972.jpg','Copenhagen 1972 [Disc 1]','No description'),
	(151,'DeepPurple_Paris1975.jpg','Live In Paris 1975 [Disc 1]','No description'),
	(152,'DeepPurple_Paris1975.jpg','Live In Paris 1975 [Disc 2]','No description'),
	(153,'Departed.jpg','The Departed','No description'),
	(154,'Departed234.jpg','The Departed','No description'),
	(155,'DireStraits_Making Movies.jpg','Making Movies','No description'),
	(156,'DireStraits_MakingMovies.png','Making Movies','No description'),
	(157,'Dire_Straights_Brothers in Arms.jpg','Brothers in Arms','No description'),
	(158,'DixieChicks_Taking The Long Way.jpg','Taking The Long Way','No description'),
	(159,'DoobieBrothers_Best Of The Doobies.jpg','Best Of Doobies','No description'),
	(160,'DoobieBrothers_BestOfDoobies.jpg','Best Of Doobies','No description'),
	(161,'DoobieBrothers_Best_of_Doobies.jpeg','Best Of Doobies','No description'),
	(162,'DoobieBrothers_CaptainAndMe.jpg','The Captain And Me','No description'),
	(163,'DoobieBrothers_Cycles.jpg','Cycles','No description'),
	(164,'DoobieBrothers_One Step Closer.jpg','One Step Closer','No description'),
	(165,'DoobieBrothers_Stampede.jpg','Stampede','No description'),
	(166,'DoobieBrothers_Takin_It_To_Streets.jpg','Takin It To The Streets','No description'),
	(167,'DoobieBrothers_The Captain And Me.jpg','The Captain And Me','No description'),
	(168,'DoobieBrothers_Toulouse Street.jpg','Toulouse Street','No description'),
	(169,'DoobieBrothers_ToulouseStreet.jpg','Toulouse Street','No description'),
	(170,'DoobieBrothers_What were Vices.jpg','What Were Vices Are Now Habits','No description'),
	(171,'DoobieBrothers_What_Were_Once_Vices_Are_Now_Habits.jpg','What Were Vices Are Now Habits','No description'),
	(172,'DoobieBrothers_What_Were_Vices.jpg','What Were Vices Are Now Habits','No description'),
	(173,'DoobieBrothers_World_Gone_Crazy.jpg','World Gone Crazy','No description'),
	(174,'DoobieBrothers_doobies1cover.gif','Not Used','No description'),
	(175,'Doors_Best of the Doors.jpg','Best of the Doors','No description'),
	(176,'Doors_BestOfDoors.jpg','Best of the Doors','No description'),
	(177,'Doors_TheDoors.jpg','Best of the Doors','No description'),
	(178,'Dovrak.jpeg','Dvoraks Greatest Hits','No description'),
	(179,'Dr-John-Goin-Back-to-New-Orleans.jpg','Goin Back To New Orleans','No description'),
	(180,'DriveByTruckerAustinTx.jpg','Live From Austin, TX','No description'),
	(181,'ELO Discovery.jpg','Discovery','No description'),
	(182,'ELO Eldorado.jpg','Eldorado','No description'),
	(183,'ELO Face The Music.jpg','Face The Music','No description'),
	(184,'ELO_Out Of The Blue.jpg','Out Of The Blue','No description'),
	(185,'Eagles.jpg','Eagles','No description'),
	(186,'Eagles_Hell Freezes Over.jpg','Hell Freezes Over','No description'),
	(187,'Eagles_Hell_Freezes_Over.jpg','Hell Freezes Over','No description'),
	(188,'Eagles_Hotel California.jpg','Hotel California','No description'),
	(189,'Eagles_One Of These Nights.jpg','One of These Nights','No description'),
	(190,'Eagles_TheEagles-OntheBorder.jpg','On The Border','No description'),
	(191,'Eagles_Their_Greatest_Hits.jpg','Their Greatest Hits','No description'),
	(192,'EarthWind&Fire_GreatestHists.jpg','Earth, Wind & Fire_ Greatest Hits','No description'),
	(193,'Edith Piaf.bmp','Not Used','No description'),
	(194,'EltonJohn_CaptainAndKid.jpg','The Captain & The Kid','No description'),
	(195,'Elviss Christmas Album.jpg','Elviss Christmas Album','No description'),
	(196,'EmmylouHarrisLightoftheStable3.jpg','Light of the Stable','No description'),
	(197,'EmmylouHarrisRedDirtGirl.jpg','Red Dirt Girl','No description'),
	(198,'EmmylouHarris_All I Intended To Be.jpg','All I Intended To Be','No description'),
	(199,'EmmylouHarris_All The Road Running.jpg','All the Road Running','No description'),
	(200,'EmmylouHarris_Elite Hotel.gif','Elite Hotel','No description'),
	(201,'EmmylouHarris_Heartaches & Highways The Very Best of Emmylou Harris.jpg','Heartaches & Highways_ The Very Best of Emmylou Harris','No description'),
	(202,'EmmylouHarris_WreckingBall.jpg','Wrecking Ball','No description'),
	(203,'EricClapton_JJCale.jpg','Live In San Diego With Special Guest JJ Cale Disc 1','No description'),
	(204,'EricClapton_JJCale.jpg','Live In San Diego With Special Guest JJ Cale Disc 2','No description'),
	(205,'EricClapton_RidingWithTheKing.jpg','Riding With The King','No description'),
	(206,'EricClapton_The_Complete.jpg','Complete Clapton [Disc 1]','No description'),
	(207,'EricClapton_The_Complete.jpg','Complete Clapton [Disc 2]','No description'),
	(208,'Eric_Clapton_Unplugged.jpg','Unplugged','No description'),
	(209,'EverlyBrothers.jpg','Cadence Classics_ Their 20 Greatest Hits','No description'),
	(210,'Fats_Waller.jpg','Fats Waller_ Very Best of Fats Waller','No description'),
	(211,'FleetwoodMac_Rumours.jpg','Rumours','No description'),
	(212,'Fleetwood_Mac_Greatest_Hits.jpg','Fleetwood Mac Hits','No description'),
	(213,'Fleetwood_Mac_Say_You_Will.jpg','Say You Will','No description'),
	(214,'FloridaGeargiaLine_AnythingGoes.jpg','Anything Goes','No description'),
	(215,'Fog_Hat_Drivin.jpg','Drivin Wheels_ Best Of 1972-1982 [Disc 1]','No description'),
	(216,'Fog_Hat_Drivin.jpg','Drivin Wheels_ Best Of 1972-1982 [Disc 2]','No description'),
	(217,'FourTops_50th.jpg','50th Anniversary Anthology [Disc 1]','No description'),
	(218,'FourTops_50th.jpg','50th Anniversary Anthology [Disc 2]','No description'),
	(219,'Frank Sinatra.jpg','The Reprise Collection [Disc 1]','No description'),
	(220,'Frank Sinatra.jpg','The Reprise Collection [Disc 2]','No description'),
	(221,'Frank Sinatra.jpg','Reprise Collection [Disc 4]','No description'),
	(222,'Frank Sinatra.jpg','The Reprise Collection [Disc 3]','No description'),
	(223,'FrankSinatra_THE_REPRISE_COLLECTION.jpg','The Reprise Collection [Disc 3]','No description'),
	(224,'GarfunkelAlbum.jpg','Garfunkel','No description'),
	(225,'Garfunkle.jpg','Garfunkel','No description'),
	(226,'Gary_Burton_Times_Square.jpg','Times Square','No description'),
	(227,'Genesis83.jpg','Genesis','No description'),
	(228,'GordonLightfoot_GordsGold.jpg','Gords Gold','No description'),
	(229,'GrandFunkRailroad_greatesthits.jpg','Grand Funk Railroad Greatest Hits','No description'),
	(230,'GratefulDead.jpg','The Grateful Dead [Bonus Tracks]','No description'),
	(231,'GratefulDead_Fare-Thee-Well-concert-poster.jpg','The Best Of Fare Thee Well - Celebrating 50 Years Of Grateful Dead_ Soldier Field, Chicago, Illinois 7_3-5_15','No description'),
	(232,'GratefulDead_In The Dark.jpg','The Best Of FIn The Dark','No description'),
	(233,'GratefulDead_In_The_Dark.jpg','The Best Of FIn The Dark','No description'),
	(234,'GratefulDead_The Best Of Grateful Dead Fare Thee Well.jpg','The Best Of Fare Thee Well - Celebrating 50 Years Of Grateful Dead_ Soldier Field, Chicago, Illinois 7_3-5_15','No description'),
	(235,'GratefulDead_Two from the Vault.jpg','Two from the Vault Disc 2','No description'),
	(236,'GratefulDead_Two from the Vault.jpg','Two from the Vault Disc 1','No description'),
	(237,'GratefulDead_What_a_Long_Strange_Trip_Its_Been.jpg','What A Long Strange Trip','No description'),
	(238,'Grateful_Dead_-_American_Beauty.jpg','American Beauty','No description'),
	(239,'Grateful_Dead_-_Anthem_of_the_Sun.jpg','Anthem Of The Sun','No description'),
	(240,'Grateful_Dead_-_In_the_Dark.jpg','In The Dark','No description'),
	(241,'Grateful_Dead_GratefulDead_Bonus_track.jpg','The Grateful Dead [Bonus Tracks]','No description'),
	(242,'Grateful_Dead_The_Grateful_Dead.jpg','The Grateful Dead [Bonus Tracks]','No description'),
	(243,'Grateful_Dead_What_a_Long_Strange_Trip_Its_Been.jpg','What A Long Strange Trip','No description'),
	(244,'Grateful_Dead_WorkmansDead.jpg','Workingmans Dead','No description'),
	(245,'GreggAllman_BackToMacon.jpg','Live Back To Macon GA Disc 1','No description'),
	(246,'Gregg_Allman_Back_to_Macon_GA.jpg','Live Back To Macon GA Disc 2','No description'),
	(247,'GuessWho_American_Woman45.jpg','American Woman','No description'),
	(248,'GuessWho_Rockin.jpg','Rockin Guess Who','No description'),
	(249,'GunsnRosesAppetiteforDestructionalbumcover.jpg','Appetite For Destruction','No description'),
	(250,'HankWilliams.jpg','24 of Hank Williams Greatest Hits','No description'),
	(251,'Harry Belefonte.jpeg','This Is Harry Belafonte','No description'),
	(252,'Heart_Beautiful_Broken.jpg','Beautiful Broken','No description'),
	(253,'HerbieHancock_Future 2 Future.jpg','Future 2 Future','No description'),
	(254,'HermansHermits_TheVeryBestOf.jpg','The Very Best Of Hermans Hermits','No description'),
	(255,'HotTuna.jpg','Hot Tuna','No description'),
	(256,'Ike_Tina_Turner.jpeg','What You Hear Is What You Get','No description'),
	(257,'Im Not There.jpg','Im Not There [Disc 1]','No description'),
	(258,'Im Not There.jpg','Im Not There [Disc 2]','No description'),
	(259,'Im_Not_There_Soundtrack_Cover.jpg','Im Not There [Disc 2]','No description'),
	(260,'IronButterfly_Inagaddadavida.jpeg','In-A-Gadda-Da-Vida','No description'),
	(261,'J.L.W.jpeg','J.L.W_','No description'),
	(262,'JLW.jpeg','J.L.W_','No description'),
	(263,'JA_Essential.jpg','The Essential Jefferson Airplane [Disc 1]','No description'),
	(264,'JA_Essential.jpg','The Essential Jefferson Airplane [Disc 2]','No description'),
	(265,'JJCale_Role_On.jpg','Roll On','No description'),
	(266,'JJ_Cale.jpg','The Definitive Collection','No description'),
	(267,'JamesGangGreatestHits.jpg','James Gang_ Greatest Hits','No description'),
	(268,'JamesGang_Funk300.jpg','James Gang_ Greatest Hits','No description'),
	(269,'JamesMorrison_Undiscovered.jpg','Undiscovered','No description'),
	(270,'JanisJoplin_greatesthits.jpg','Janis Joplins Greatest Hits [10 Tracks]','No description'),
	(271,'JanisJoplin_supeHit_Joplin.jpg','Super Hits Janis Joplin','No description'),
	(272,'JazzCrusaders_Crusader 1.jpg','Crusaders 1','No description'),
	(273,'JazzCrusaders_Free As the Wind.jpg','Free As The Wind','No description'),
	(274,'JazzCrusaders_Jazz_Crusaders_1961-1965.jpg','The Best Of The Jazz Crusaders 1961 - 1965','No description'),
	(275,'JazzCrusaders_Southern Comfort.jpg','Southern Comfort','No description'),
	(276,'JazzCrusaders_The Best Of The Jazz Crusaders.jpg','The Best of the Jazz Crusaders','No description'),
	(277,'JeffBeck_Best_of_Beck.jpg','Best Of Beck','No description'),
	(278,'JeffBeck_Loud Hailer.jpg','Loud Hailer','No description'),
	(279,'JeffersonAirplane_Surrealistic Pillow.jpeg','Surrealistic Pillow','No description'),
	(280,'JimCroce_Photographsandmemories.jpg','Photographs & Memories_ His Greatest Hits','No description'),
	(281,'JimmiHendrix_Are_u_experienced.jpg','Are You Experienced_','No description'),
	(282,'JimmiHendrix_rainbow bridge.jpg','Rainbow Bridge','No description'),
	(283,'JimmiHendrix_south saturn.jpg','South Saturn Delta','No description'),
	(284,'Jimmy Whiterspoon.jpg','The Best Of Jimmy Witherspoon','No description'),
	(285,'JimmyWitherspoon_LiveAt1972MontereyJazz Festival.jpg','Live At the 1972 Monterey Jazz Festival (feat. Robben Ford)','No description'),
	(286,'Joan Baez Noel.jpeg','Noel','No description'),
	(287,'JoanBaez Blessed_Are.jpg','Blessed Are','No description'),
	(288,'JoanBaez Gulf Winds.jpg','Gulf Winds(8_29_2004 1_30_11 PM)','No description'),
	(289,'JoanBaez_10years.jpg','1st 10 years','No description'),
	(290,'JoanBaez_First 10 Years.jpg','1st 10 years','No description'),
	(291,'JoanBaez_Any Day Now.jpg','Any Day  Now','No description'),
	(292,'JoanBaez_Farewell_Angeline.jpeg','Farewell, Angelina','No description'),
	(293,'JoeCocker Greatest Hits.jpg','Joe Cocker''s Greatest Hits','No description'),
	(294,'JoeCocker Little Rain.jpg','I Can Stand A Little Rain','No description'),
	(295,'JoeCocker.jpg','You Are So Beautiful','No description'),
	(296,'John Fahey Leo Kottke Peter Lang.jpg','Leo Kottke-John Fahey-Peter Lang','No description'),
	(297,'JohnColtrane Greatest Hist.jpg','John Coltrane His Greatest Years','No description'),
	(298,'JohnColtrane His Greatest Years.jpg','John Coltrane His Greatest Years','No description'),
	(299,'JohnColtrane_-_Live_at_the_Village_Vanguard_Again.jpg','Coltrane Live At the Village Vangard Again!','No description'),
	(300,'JohnColtrane_BlueTrane3.jpg','Blue Train [Expanded Edition]','No description'),
	(301,'JohnColtrane_Blue_Train.jpg','Blue Train [Expanded Edition]','No description'),
	(302,'JohnColtrane_Impressions.jpg','Impressions','No description'),
	(303,'JohnColtrane_Live_in_Seattle.jpg','Live in Seattle [Disc 1]','No description'),
	(304,'JohnColtrane_Live_in_Seattle.jpg','Live in Seattle [Disc 2]','No description'),
	(305,'JohnColtrane_Newport_63.jpg','Newport ''63 [Live]','No description'),
	(306,'JohnColtrane_prestige_7105.jpg','Coltrane_Prestige 7105','No description'),
	(307,'JohnLennon_Imagine_lennon.jpg','Imagine','No description'),
	(308,'JohnLennon_Legend of Lennon.jpg','Lennon Legend The Very Best of John Lennon','No description'),
	(309,'JohnLennon_RockNRoll.jpg','Rock ''N'' Roll','No description'),
	(310,'JohnMayall_ABC Years.jpg','Drivin'' On_ The ABC Years (1975-1982) Disc 1','No description'),
	(311,'JohnMayall_ABC Years.jpg','Drivin'' On_ The ABC Years (1975-1982) Disc 2','No description'),
	(312,'JohnMayall_FindAwayToCare.jpeg','Find A Way To Care','No description'),
	(313,'JohnMayall_Find_A_Way_To_Care.jpeg','Find A Way To Care','No description'),
	(314,'JohnMayall_Padloack On The Blues.jpg','Padlock On The Blues','No description'),
	(315,'JohnPrine_In_Spite_of_Ourselves.jpg','In Spite of Ourselves','No description'),
	(316,'JohnPrine_Lost_Dogs_and_Mixed_Blessings.jpg','Lost Dogs and Mixed Blessings','No description'),
	(317,'John_Prine.jpg','John Prine','No description'),
	(318,'JohnnyWinterRoots.jpg','Roots','No description'),
	(319,'JohnnyWinterStepBack.jpg','Step Back','No description'),
	(320,'JohnnyWinter_2nd Winter.jpg','2nd Winter','No description'),
	(321,'JohnnyWinter_BestOfJohnnyWinter.jpg','The Best of Johnny Winter','No description'),
	(322,'JohnnyWinter_Im A Blue Man.jpg','I''m a Bluesman','No description'),
	(323,'JohnnyWinter_Second Winter.jpg','2nd Winter','No description'),
	(324,'Johnny_Winter-Im_a_Bluesman.jpg','I''m a Bluesman','No description'),
	(325,'Johnny_Winter_Still_Alive_and_Well_Coverart.jpg','Still Alive and Well','No description'),
	(326,'Johnnywinter_ProgressiveBluesExperiment.jpg','The Progressive Blues Experiment','No description'),
	(327,'Jonny Cash.jpg','Sunday Morning Coming Down','No description'),
	(328,'JudeyCollins.jpg','Judy Collins','No description'),
	(329,'JudyCollins_Bothsides.jpg','Both Sides Now_ The Very Best Of','No description'),
	(330,'JudyCollins_Bothsides.jpg','Both Sides Now - The Very Best Of [Disc 2]','No description'),
	(331,'KeithJarret_SoloConcerts.jpg','Solo Concerts_ Bremen [Live]','No description'),
	(332,'KeithJarret_SoloConcerts.jpg','Solo Concerts_ Lausanne [Disc 2]','No description'),
	(333,'KeithUrban_Fuse.jpg','Keith Urban _ Fuse','No description'),
	(334,'KennyGarret_Beyond The Wall.jpg','Not Used','No description'),
	(335,'Kingsmen.jpg','The Best of The Kingsmen','No description'),
	(336,'Kingsmen.jpg','Louie Louie_ The Very Best of The Kingsmen','No description'),
	(337,'Kinks-size.jpg','Kinks-Size','No description'),
	(338,'Kinks.jpg','Kinks','No description'),
	(339,'Kinks_Lola.jpg','Lola Versus Powerman And The Moneygoround, Part One','No description'),
	(340,'Kiss_Rock_and_roll_over_cover.jpg','Rock And Roll Over','No description'),
	(341,'KristoffersonAlbumCover.jpg','Kristofferson','No description'),
	(342,'KristoffersonTheSilverTonguedDevilandI.jpg','Silver Tongued Devil And I','No description'),
	(343,'Laura Nyro.jpg','Not Used','No description'),
	(344,'LedZepplin_Song Remains Same.jpg','The Song Remains the Same Disc 1','No description'),
	(345,'LedZepplin_Song Remains Same.jpg','The Song Remains the Same Disc 2','No description'),
	(346,'LedZepplin_Sound_Remains_Same.jpeg','The Song Remains the Same Disc 2','No description'),
	(347,'Leo Kottke.jpeg','Leo Kottke-John Fahey-Peter Lang','No description'),
	(348,'LeoSayer.jpeg','Leo Sayer','No description'),
	(349,'LesMcCannEddieHarris_Swiss Movement.jpg','Swiss Movement','No description'),
	(350,'LesMcCannEddieHarris_SwissMovement.jpg','Swiss Movement','No description'),
	(351,'Lester-Young-Mean-To-Me.jpg','Mean To Me','No description'),
	(352,'LindaRonstadt_Dont Cry Now.jpg','Don''t Cry Now','No description'),
	(353,'LindaRonstadt_Dont_Cry_Now.jpg','Don''t Cry Now','No description'),
	(354,'LindaRonstadt_Heart Like A Wheel.jpg','Heart Like A Wheel','No description'),
	(355,'LindaRonstadt_JustOneLookClassic.jpeg','Just One Look_ Classic Linda Ronstadt','No description'),
	(356,'LindaRonstadt_Simple_Dreams_Album_Cover.jpg','Simple Dreams','No description'),
	(357,'LosBravos_black is black.jpg','Los Bravos Single','No description'),
	(358,'LosLobos_Kiko_Live.jpg','Kiko Live','No description'),
	(359,'LouiArmstrong_main_armstrong.jpg','Not Used','No description'),
	(360,'Lovin Spoonful.jpg','Lovin Spoonful Anthology','No description'),
	(361,'LovinSpoonfulAnthology.jpg','Lovin Spoonful Anthology','No description'),
	(362,'LynardSkynard_Gimme Back Bullets.jpg','Gimme Back My Bullets','No description'),
	(363,'LynardSkynard_One More For The Road.jpg','One From The Road','No description'),
	(364,'Marvin Gaye''s Greatest Hist.jpg','Marvin Gaye''s Greatest Hits','No description'),
	(365,'Masked And Anonymous.jpg','Masked & Anonymous','No description'),
	(366,'Masked_and_Anonymous_poster1.jpg','Masked & Anonymous','No description'),
	(367,'Mavericks_Mono.jpg','Mono','No description'),
	(368,'MavisMaples_OnlyLonely.jpg','Only For The Lonely','No description'),
	(369,'MavisMaples_Only_For_Lonely.jpg','Only For The Lonely','No description'),
	(370,'Mayall_ABC_DrivinYears.jpg','Drivin'' On_ The ABC Years (1975-1982) Disc 2','No description'),
	(371,'Mayall_ABC_DrivinYears.jpg','Drivin'' On_ The ABC Years (1975-1982) Disc 1','No description'),
	(372,'Meatloaf_Bat_out_of_Hell.jpg','Bat Out Of Hell','No description'),
	(373,'MenAtWork_BizAsUsual.png','Business As Usual','No description'),
	(374,'Men_AT_Work_Down_Under_australia_single.jpg','Driving Music','No description'),
	(375,'MichealBrecker_MichealBrecker.jpg','Michael Brecker','No description'),
	(376,'Midnight_LoreenaMcKennitt.jpg','A Midwinter Night''s Dream','No description'),
	(377,'MileDavis_Kind Of Blue.jpg','Kind Of Blue','No description'),
	(378,'MilesDavisBirth_0f_Cool.jpg','Birth of the Cool','No description'),
	(379,'MilesDavis_Bitches Brew.jpg','Bitches Brew Disc 1','No description'),
	(380,'MilesDavis_Bitches Brew.jpg','Bitches Brew Disc 2','No description'),
	(381,'MilesDavis_Filles De Kilimanjaro.jpg','Filles De Kilimanjaro','No description'),
	(382,'MilesDavis_Milestonescover.jpg','Milestones','No description'),
	(383,'MilesDavis_Workin With The Miles Davis Quintet.jpg','Workin'' With The Miles Davis Quintet','No description'),
	(384,'MilesDavis_Workin With Monk_Criss Cross.jpg','Thelonious Monk','No description'),
	(385,'MoodyBlues_for the children.jpg','To Our Children''s Children''s Children','No description'),
	(386,'Moody_Blues_days of future passed.jpg','Days Of Future Passed','No description'),
	(387,'Moodyblues_In Search Lost Chord.jpg','In Search Of the Lost Chord','No description'),
	(388,'Motorhead_Bad_Magic.jpg','Bad Magic','No description'),
	(389,'NGDB-DirtSilverGold.jpg','Dirt Siver Gold','No description'),
	(390,'Neil Diamond Collection.jpg','The Neil Diamond Collection','No description'),
	(391,'NeilYoung_LivignWithWar.jpg','Living With War','No description'),
	(392,'NeilYoung_TheLostTapes_Young.jpg','Live On Air The Lost Tapes Vol. 2','No description'),
	(393,'Nirvana-Incesticide.jpg','Incesticide','No description'),
	(394,'OliviaNewtonJohn.jpg','Olivia Newton-John','No description'),
	(395,'PatMethany_80-81.jpg','80_81','No description'),
	(396,'PatMethany_American Garage.jpg','American Garage','No description'),
	(397,'Patsy_Cline''s_Greatest_Hits.jpg','Patsy Cline''s Greatest Hits (Remastered)','No description'),
	(398,'PattiSmith Radio Ethiopia.jpg','Radio Ethiopia','No description'),
	(399,'PattiSmith_Easter.jpg','Easter','No description'),
	(400,'PattiSmith_Gone_Again.jpg','Gone Again','No description'),
	(401,'PattiSmith_Gung_Ho.jpg','Gung Ho','No description'),
	(402,'PattiSmith_Outside_Society.jpg','Outside Society','No description'),
	(403,'PattiSmith_Twelve.jpg','Twelve','No description'),
	(404,'PaulButterfield 1965.jpg','The Paul Butterfield Blues Band','No description'),
	(405,'PaulButterfield Blues Band.jpg','The Paul Butterfield Blues Band','No description'),
	(406,'PaulButterfield_East-West.jpg','East-West','No description'),
	(407,'Paul_McCartney_&_Wings-Band_on_the_Run_album_cover.jpg','Band on the Run','No description'),
	(408,'Pete Seeger & Arlo Guthrie .jpg','Pete Seeger & Arlo Guthrie - Together In Concert','No description'),
	(409,'PeteTownsend_Rough Mix.jpg','Rough Mix','No description'),
	(410,'PeterPaulMary_See What Tomorrow Brings.jpg','See What Tomorrow Brings','No description'),
	(411,'PinkFloyd_More.jpg','More_ Original Motion Picture Soundtrack','No description'),
	(412,'Poco.jpg','Ultimate Collection','No description'),
	(413,'Pointer_Sisters_Breakout.jpg','Breakout','No description'),
	(414,'PrairieFlyer_oldDog.jpg','Just an Old Dog','No description'),
	(415,'Pretenders_The_Pretenders_Alone.jpg','Alone','No description'),
	(416,'Queen_At_Wimberly.jpg','Live At Wembley Stadium [Disc 1]','No description'),
	(417,'Queen_At_Wimberly.jpg','Live At Wembley Stadium [Disc 2]','No description'),
	(418,'R.E.M._-_Collapse_into_Now.jpg','Collapse Into Now','No description'),
	(419,'R.E.M._-_Collapse_into_Now.jpg','REM_Collapse Into Now.jpg','No description'),
	(420,'Radiohead.amnesiac.albumart.jpg','Amnesiac','No description'),
	(421,'Rat_Pack.jpeg','Rat Pack_ Members Edition [Live]','No description'),
	(422,'Reminiscing_Atkins_Snow.jpg','Reminiscing','No description'),
	(423,'Rider Of The Purple Sage.jpg','Best of the West','No description'),
	(424,'Ringo_Photograph-TheVeryBestOfRingoStarr_cover_art.jpg','Photograph_ The Very Best Of Ringo Starr','No description'),
	(425,'Rita Coolige.jpeg','Delta Lady _ The Anthology','No description'),
	(426,'Ritchie_Valens_Donna_single.jpg','50''s Rock','No description'),
	(427,'RodStewart_Maggie_may.jpg','Driving Music','No description'),
	(428,'RollingStonesSingle.jpeg','Singles Collection_ The London Years [Disc 1]','No description'),
	(429,'RollingStonesSingle.jpeg','Singles Collection_ The London Years [Disc 2]','No description'),
	(430,'RollingStonesSingle.jpeg','Singles Collection_ The London Years [Disc 3]','No description'),
	(431,'Ronstadt_Harris_TheTucsonSessions.jpg','Western Wall_ The Tucson Sessions','No description'),
	(432,'Roy Orbison.bmp','For the Lonely_ 18 Greatest Hits','No description'),
	(433,'Santana-All_That_I_Am.jpg','All That I Am','No description'),
	(434,'Santana-Supernatural.jpg','Supernatural','No description'),
	(435,'Santana_AllThatIam.jpg','All That I Am','No description'),
	(436,'Santanna_abraxas.jpg','Abraxas','No description'),
	(437,'SantoAndJohnny_Sleep_Walk.jpg','50''s Rock','No description'),
	(438,'SavoyBrown_savoybrowncover.JPG','Boogie Brothers','No description'),
	(439,'SavoyBrown_spsavoybrowncover.gif','Boogie Brothers','No description'),
	(440,'Scofieldagogo.jpg','A Go Go','No description'),
	(441,'Seals_Crofts_Greatest.jpg','Seals & Crofts Greatist Hits','No description'),
	(442,'SimonAndGarfunkel_Bridge_over_Troubled_Water_(1970).png','Bridge Over Troubled Water','No description'),
	(443,'SimonAndGarfunkle_Greatest Hits Simon & Garfunkel.jpg','Greatest Hits Simon & Garfunkel','No description'),
	(444,'SingingWinthEmmylouHarris.jpg','Singin'' With Emmylou Volume 1 (P) 2000','No description'),
	(445,'SonnyRollins_Mambo_Bounce.jpeg','Mambo Bounce','No description'),
	(446,'SonnyRollins_Mambo_Bounce.jpg','Mambo Bounce','No description'),
	(447,'Springsteen_High_Hopes_album.jpg','High Hopes','No description'),
	(448,'Steve Goodman.jpg','Steve Goodman','No description'),
	(449,'StevieRayVaugn_Stevie Ray Vauhn DoubleTrouble.bmp','Stevie Ray Vaughan & Double Trouble_ Live At Carnegie Hall','No description'),
	(450,'SteviewRayVaughn Stevie Ray Vaughn 2.bmp','Martin Scorsese Presents_ Stevie Ray Vaughan','No description'),
	(451,'StrayCats_Built_For_Speed_cover.jpg','Built For Speed','No description'),
	(452,'Stringdusters_fork.jpg','Fork in the Road','No description'),
	(453,'Styx-Cornerstone.jpg','Cornerstone','No description'),
	(454,'THEM.jpg','Them Featuring Van Morrison','No description'),
	(455,'TalkingHeads_True Stories.jpg','True Stories','No description'),
	(456,'Ten Years After Cover.gif','A Space In Time','No description'),
	(457,'Ten Years After.jpg','Not Used','No description'),
	(458,'TenyearsAfter_tenyearsaftercover.gif','A Space In Time','No description'),
	(459,'TheBand Greatest Hits.jpg','Greatest Hits [Remastered] [UK]','No description'),
	(460,'TheBand_Last_Waltz.jpg','The Last Waltz [2003 Remaster] Disc 2','No description'),
	(461,'TheBand_The Last Waltz.jpg','The Last Waltz [2003 Remaster] Disc 1','No description'),
	(462,'TheCars_Move_Like_This_album_cover.jpg','Move Like This','No description'),
	(463,'TheMonkees_Hits.jpg','The Monkees Greatest Hits','No description'),
	(464,'The_Byrds.jpeg','Super Hits The Byrds','No description'),
	(465,'ThreeDogNight_The_Bestof3DogNight.jpg','Best Of Three Dog Night','No description'),
	(466,'TinaTurner_Private_Dancer.jpg','Private Dancer','No description'),
	(467,'TinaTurner_what you hear is what you get.jpg','What You Hear Is What You Get','No description'),
	(468,'Traffic-Welcome_to_the_Canteen.jpg','Welcome To The Canteen [Live]','No description'),
	(469,'Traffic_When The Eagle Flies.jpeg','When The Eagle Flies','No description'),
	(470,'Traffic_album.jpg','Traffic','No description'),
	(471,'TravWilb1Cover.jpg','The Traveling Wilburys, Vol. 1','No description'),
	(472,'UncleEarl_she waits for the night.jpg','She Waits for Night','No description'),
	(473,'Union_Gap.jpg','Union Gap','No description'),
	(474,'VanMorrison_Borntosingnoplanb.jpg','Blowin'' Your Mind!','No description'),
	(475,'War.jpg','Platinum Jazz','No description'),
	(476,'Waylon and Willie.jpeg','Waylon and Willie','No description'),
	(477,'WaylonJenningsHonkyTonkHeroes.jpg','Honky Tonk Heroes','No description'),
	(478,'WaylonJennings_What Goes Around Comes Around.jpeg','What Goes Around Comes Around','No description'),
	(479,'Waylon_Collaboration.jpg','The Music Inside - A Collaboration Dedicated to Waylon Jennings, Vol. 1','No description'),
	(480,'Waylon_Collaboration.jpg','The Music Inside_ A Collaboration Dedicated To Waylon Jennings, Volume II','No description'),
	(481,'WeatherReport_Night Passage.jpg','Night Passage','No description'),
	(482,'Weather_Report-Heavy_Weather.jpg','Heavy Weather','No description'),
	(483,'Weather_Report_Black_Market.jpg','Black Market','No description'),
	(484,'Who_Tommyalbumcover.jpg','Tommy','No description'),
	(485,'Willie Nelson Always.jpg','Not Used','No description'),
	(486,'WillieNelsonAndLeonRussell.jpg','Willie Nelson and Leon Russel','No description'),
	(487,'Woody Gutherie.jpg','Not Used','No description'),
	(488,'Yes_Best_of_Yes.jpg','The Very Best of Yes','No description'),
	(489,'Yes_The Yes Album.jpg','The Yes Album','No description'),
	(490,'ZacBrown_Pass_the_jar.jpg','Pass The Jar_ Zac Brown Band And Friends Live From The Fabulous Fox Theatre In Atlanta [Disc 1]','No description'),
	(491,'ZacBrown_Pass_the_jar.jpg','Pass The Jar_ Zac Brown Band And Friends Live From The Fabulous Fox Theatre In Atlanta [Disc 2]','No description'),
	(492,'bluesSelects.jpg','Blues Selects','No description'),
	(493,'chuck_berry.jpg','The Best of Chuck Berry','No description'),
	(494,'citizen_cope.jpg','Every Waking Moment','No description'),
	(495,'coltrane Jazz Manefesto.jpeg','Jazz Manifesto','No description'),
	(496,'creedence gold.jpg','Creedence Gold','No description'),
	(497,'guns_roses_appetite.jpg','Appetite For Destruction','No description'),
	(498,'gypsy soul.jpg','Gypsy Soul New Flamenco','No description'),
	(499,'hair_music.jpg','Hair','No description'),
	(500,'jazz_selects.jpg','Jazz Selects','No description'),
	(501,'kingston trio.jpg','Absolutely The Best','No description'),
	(502,'miles davis classic ballads.jpg','Classic Ballads','No description'),
	(503,'miles davis classic ballads.jpg','Classic Ballads','No description'),
	(504,'muddy waters boot leg.jpg','Authorized Bootleg - Fillmore Auditorium, San Francisco Nov. 4-6 1966','No description'),
	(505,'musique aux diogts.JPG','Not Used','No description'),
	(506,'ramble2014-web.jpg','Not Used','No description'),
	(507,'riders_cody_bryant.jpg','Cody Bryant and The Riders Of The Purple Sage','No description'),
	(508,'righteous brothers.jpg','Anthology_ 1962-1974 [Disc 1]','No description'),
	(509,'righteous brothers.jpg','Anthology 1962-1974 [Disc 2]','No description'),
	(510,'santana-all_that_i_am_a.jpg','All That I Am','No description'),
	(511,'song from the mountain.jpg','Songs from the Mountain','No description'),
	(512,'sonics.jpg','This Is the Sonics','No description'),
	(513,'white_lion.jpg','The Best Of White Lion','No description'),
	(514,'Wagne_A_Concert.jpeg','A Wagner Concert','No description'),
	(515,'MichaelMurphey_CowBoysongs.jpg','Cowboy Songs 3','No description'),
	(516,'BillieHolliday.jpg','Best Of Billy Holliday','No description'),
	(517,'FatsWaller_TheVeryBest.jpg','Fats Waller_ Very Best of Fats Waller','No description'),
	(518,'NielDiamond_TheCollection.jpg','The Neil Diamond Collection','No description'),
	(519,'LindaRonstadt_Duets.jpg','Duets','No description'),
	(520,'Billie Holiday.jpeg','The Billie Holiday Story Volume II','No description'),
	(521,'Yes_Going_for_the_One.jpg','Going For The One [Bonus Tracks]','No description'),
	(522,'Neil_Young_&_Crazy_Horse-Live_Rust.jpg','Live Rust','No description'),
	(523,'NeilYoung_Psychedelicpill.jpg','Psychedelic Pill [Disc 2]','No description'),
	(524,'The_who_sell_out.jpg','The Who Sell Out','No description'),
	(525,'Queenryche_Takecover.jpg','Take Cover','No description'),
	(526,'WilsonPicket_The_Exciting.jpeg','The Exciting Wilson Pickett','No description'),
	(527,'JeffBeck_Live+.jpeg','Live+','No description'),
	(528,'BookerT.&theMG''sGreenOnions.jpg','Green Onions','No description'),
	(529,'AndyNarell_Stickman.jpeg','Stickman','No description'),
	(530,'Clapton_I_Still_Do.jpg','I Still Do','No description'),
	(531,'Bowie_Earthling.jpg','Earthling','No description'),
	(532,'Blondie_EatTheBeat.jpg','Eat To The Beat','No description'),
	(533,'Garcia-Live-Volume-8.jpg','GarciaLive, Vol. 8 [Disc 1]','No description'),
	(534,'Garcia-Live-Volume-8.jpg','GarciaLive, Vol. 8 [Disc 2]','No description'),
	(535,'PinkFloyd_Pulse.jpg','Pulse [Disc 1]','No description'),
	(536,'PinkFloyd_Pulse.jpg','Pulse [Disc 2]','No description'),
	(537,'JerryGarciaBand_Vol_5.jpg','GarciaLive, Vol. 5 [Disc 1]','No description'),
	(538,'JerryGarciaBand_Vol_5.jpg','GarciaLive, Vol. 5 [Disc 2]','No description'),
	(539,'EricClapton_Crossroads.jpg','Crossroads Guitar Festival 2013 [Live] [Disc 1]','No description'),
	(540,'EricClapton_Crossroads.jpg','Crossroads Guitar Festival 2013 [Live] [Disc 2]','No description'),
	(541,'LesterYoung_Pres.jpeg','Pres','No description'),
	(542,'JimiHendrix_BlueWildAngel.jpg','Blue Wild Angel_ Jimi Hendrix Live At The Isle Of Wight','No description'),
	(543,'LenardCohen_cantforget.jpg','Can''t Forget_ A Souvenir of the Grand Tour','No description'),
	(544,'BlueOysterCult_The_Essential.jpg','The Essential Blue Oyster Cult','No description'),
	(545,'Beck_Morning_Phase.jpg','Morning Phase','No description'),
	(546,'Foghat_The_BestOf.jpg','The Best Of Foghat','No description'),
	(547,'GratefulDead_best_of_2015.jpg','The Best Of Fare Thee Well - Celebrating 50 Years Of Grateful Dead: Soldier Field, Chicago, Illinois 7/3-5/15','No description'),
	(548,'Iron&wine_Kiss_Each_Other_Clean.jpg','Kiss Each Other Clean','No description'),
	(549,'Iron&wine_ArchiveSeriesVolume1.jpg','Archive Series, Vol. No. 1','No description'),
	(550,'DexterGordon_Homecoming.jpeg','Homecoming_ Live At The Village Vanguard [Live] [Disc 1]','No description'),
	(551,'BJThomas_GreatestHist.jpeg','B.J. Thomas_ Greatest Hits','No description'),
	(552,'Santana_IV.jpg','Santana IV','No description'),
	(553,'T_Rex_The_Slider.jpg','The Slider','No description'),
	(554,'EmersonlakePalmer_cover.jpg','Emerson, Lake & Palmer','No description'),
	(555,'Hollies_On_A_Caraousel.jpg','On a Carousel','No description'),
	(556,'Fleetwood_Mac_Greatest_Hits_1971.jpg','Fleetwood Mac''s Greatest Hits','No description'),
	(557,'REM_Accerlerate.jpeg','Accerlerate','No description'),
	(558,'DaveMason_DefintiveCollection.jpeg','Dave Mason The Definitive Collection','No description'),
	(559,'IsaacHayes_greatest_singles.jpg','Isaac Hayes Greatest Hit Singles','No description'),
	(560,'PinkFloyd_SaucersOfScrets.jpg','A Saucerful Of Secrets','No description'),
	(561,'JohnMellencamp_NothingLikeIPlanned.jpg','Nothing Like I Planned Greatst Hits Vol. 3','No description'),
	(562,'Devo_FreedomOfChoice.jpg','Freedom Of Choice [Deluxe Remastered Edition]','No description'),
	(563,'McCartney_Ram.jpg','Ram','No description'),
	(564,'LenardCohen_Songs_from_a_room.jpg','Songs From A Room','No description'),
	(565,'REM_AutomaticForPeople.jpg','Automatic For The People','No description'),
	(566,'VanMorrison_AstralWeeks.jpg','Astral Weeks','No description'),
	(567,'GrassRoots_CompleteOriginal.jpg','The Complete Original Dunhill_ABC Hit Singles','No description'),
	(568,'Heart_Heart.jpg','Heart','No description'),
	(569,'EltonJohn_YellowBrickRoad.jpg','Goodbye Yellow Brick Road','No description'),
	(570,'chicago_VIII.jpg','Chicago VIII [Bonus Tracks]','No description'),
	(571,'CrookedStill_Strange_Country.jpg','Some Strange Country','No description'),
	(572,'JohnColtrane_Ballads.jpg','Ballads (Deluxe Edition) [Disc 2]','No description'),
	(573,'BBKing_CookCountyJail.jpg','Live In Cook County Jail','No description'),
	(574,'BBKing_LiveAtRegal.jpg','Live At The Regal','No description'),
	(575,'RodStewarts_Gold.jpg','Gold [Disc 2]','No description'),
	(576,'RodStewarts_Gold.jpg','Gold [Disc 1]','No description'),
	(577,'JethroTull_Anniverary.jpg','The Best Of Jethro Tull_ The Anniversary Collection [Disc 1]','No description'),
	(578,'JethroTull_Anniverary.jpg','The Best Of Jethro Tull_ The Anniversary Collection [Disc 2]','No description'),
	(579,'\nMarsalis_UpwardSpiral.jpg','Upward Spiral','No description'),
	(580,'JohnColtrane_StarDust.jpg','Stardust','No description'),
	(581,'RodStewart_AnotherCountry.jpg','Another Country','No description'),
	(582,'Sonics_Boom.jpg','Boom','No description'),
	(583,'Lynyrdskynyrd_Pronounced.jpg','Pronounced Leh-nerd Skin-nerd','No description'),
	(584,'TalkingHeads_LittleCreatures.jpg','Little Creatures','No description'),
	(585,'TalkingHeads_77.jpg','Talking Heads_ 77','No description'),
	(586,'SpankAndOurGang_TheBestOf.jpg','The Best Of Spanky & Our Gang 20th Century Masters The Millennium Collection','No description'),
	(587,'Krauss_WindyCity.jpg','Windy City','No description'),
	(588,'MarshalTucker_CarolinaDreams.jpg','Carolina Dreams','No description'),
	(589,'Zombies_OdesseyOracle.jpg','Odessey & Oracle [Bonus Tracks]','No description'),
	(590,'PaulSimon_Graceland.jpg','Graceland: The Remixes','No description'),
	(591,'TravelingWilburys_BonusTracks.jpg','Traveling Wilburys Collection [Disc 1]','No description'),
	(592,'TravelingWilburys_BonusTracks.jpg','Traveling Wilburys Collection [Disc 3]]','No description'),
	(593,'TomWaits_BasAsMe.jpg','Bad As Me','No description'),
	(594,'TowerOfPower_GreatAmericanSoulBook.jpg','Great American Soulbook','No description'),
	(595,'MarshalTucker_whereWeAllBelong.jpg','Where We All Belong','No description');

